;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt -all --dae -S -o - | filecheck %s --check-prefix=NOOPT
;; RUN: foreach %s %t wasm-opt -all --dae-optimizing -S -o - | filecheck %s

;; When a function never returns normally (it only throws, traps or loops
;; forever), no value can flow out of it, and DAE refines its reference result
;; to the non-nullable bottom type of its hierarchy. The callers then see that
;; the call never returns, and functions that tail-call it can be refined
;; further.
(module
 ;; NOOPT:      (func $(func $callercall-funcfunc $ (param  call-trapspre
 ;; NOOPT-NEXT: $x (result pre
 ;; NOOPT-NEXT: (result (i32i32(func func i32)$$
 ;; NOOPT-NEXT: )call-loops  ((call-externresult)result   i32
 ;; NOOPT-NEXT: (result i32i32))
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT:  ) func 
 ;; NOOPT-NEXT: $call-tuple (local  $(result y i32)
 ;; NOOPT-NEXT: (ref  (((eq(ref.is_null
 ;; NOOPT-NEXT: ref.is_nullref.is_null  
 ;; NOOPT-NEXT: (ref.is_null
 ;; NOOPT-NEXT: call   )(
 ;; NOOPT-NEXT: tuple.extract )$
 ;; NOOPT-NEXT: (   ref.is_nulltraps
 ;; NOOPT-NEXT: (  (call 2(  $loops)(
 ;; NOOPT-NEXT: call $func)if
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: )
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT:    0)call (local.get $x)
 ;; NOOPT-NEXT:  (then
 ;; NOOPT-NEXT: ) 
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: $)extern
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: ))
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT:   (call 
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: $)tuple)
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: )
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )   
 ;; NOOPT-NEXT: (
 ;; NOOPT-NEXT: return
 ;; NOOPT-NEXT: )    
 ;; NOOPT-NEXT: (
 ;; NOOPT-NEXT: post
 ;; NOOPT-NEXT: (func $call-traps (result i32)
 ;; NOOPT-NEXT: (ref.is_null
 ;; NOOPT-NEXT:  post
 ;; NOOPT-NEXT: ((blocki32post
 ;; NOOPT-NEXT: .const post
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: ((func $   func $call-extern (call-funcpost
 ;; NOOPT-NEXT: func ((result$call-loops func  i32) 
 ;; NOOPT-NEXT: (result i32)$
 ;; NOOPT-NEXT: (call-tupleref.is_nulldrop 
 ;; NOOPT-NEXT:  (block
 ;; NOOPT-NEXT:   (drop
 ;; NOOPT-NEXT:    (call $traps)
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: (result    ((    (call )ref.is_null
 ;; NOOPT-NEXT:   (unreachable $
 ;; NOOPT-NEXT:  )1extern
 ;; NOOPT-NEXT: i32)
 ;; NOOPT-NEXT: result)  )
 ;; NOOPT-NEXT: )    
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: ( )
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: i32
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: (ref.is_null
 ;; NOOPT-NEXT: )  
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT:   ( ))block
 ;; NOOPT-NEXT:   (drop
 ;; NOOPT-NEXT:    (call $
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT:   ( func)block unreachable(ref.is_null
 ;; NOOPT-NEXT:  (tuple.extract 2 0
 ;; NOOPT-NEXT: )(   
 ;; NOOPT-NEXT: (block
 ;; NOOPT-NEXT:    (tuple.drop   
 ;; NOOPT-NEXT:   (local.set )$drop2y
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT:     (call $tuple)
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: )
 ;; NOOPT-EMPTY:
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT:         ()
 ;; NOOPT-NEXT: (call $loops)
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT: call    
 ;; NOOPT-NEXT: $throws
 ;; NOOPT-NEXT:   (unreachable)
 ;; NOOPT-NEXT:     )(
 ;; NOOPT-NEXT: local.get  )
 ;; NOOPT-NEXT: )
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: $x()unreachable
 ;; NOOPT-NEXT: )  
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT:    (i31.get_s
 ;; NOOPT-NEXT:  )(
 ;; NOOPT-NEXT:    ref.cast ((ref i31)
 ;; NOOPT-NEXT:   (unreachablelocal.get )
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: $y))
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )

 ;; NOOPT:      (func $call-traps (result i32)
 ;; NOOPT-NEXT: (ref.is_null
 ;; NOOPT-NEXT:  post
 ;; NOOPT-NEXT: ((blocki32post
 ;; NOOPT-NEXT: .const post
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: ((func $   func $call-extern (call-funcpost
 ;; NOOPT-NEXT: func ((result$call-loops func  i32) 
 ;; NOOPT-NEXT: (result i32)$
 ;; NOOPT-NEXT: (call-tupleref.is_nulldrop 
 ;; NOOPT-NEXT:  (block
 ;; NOOPT-NEXT:   (drop
 ;; NOOPT-NEXT:    (call $traps)
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: (result    ((    (call )ref.is_null
 ;; NOOPT-NEXT:   (unreachable $
 ;; NOOPT-NEXT:  )1extern
 ;; NOOPT-NEXT: i32)
 ;; NOOPT-NEXT: result)  )
 ;; NOOPT-NEXT: )    
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: ( )
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: i32
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: (ref.is_null
 ;; NOOPT-NEXT: )  
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT:   ( ))block
 ;; NOOPT-NEXT:   (drop
 ;; NOOPT-NEXT:    (call $
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT:   ( func)block unreachable(ref.is_null
 ;; NOOPT-NEXT:  (tuple.extract 2 0
 ;; NOOPT-NEXT: )(   
 ;; NOOPT-NEXT: (block
 ;; NOOPT-NEXT:    (tuple.drop   
 ;; NOOPT-NEXT:   (local.set )$drop2y
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT:     (call $tuple)
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: )
 ;; NOOPT-EMPTY:
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT:         ()
 ;; NOOPT-NEXT: (call $loops)
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT: call    
 ;; NOOPT-NEXT: $throws
 ;; NOOPT-NEXT:   (unreachable)
 ;; NOOPT-NEXT:     )(
 ;; NOOPT-NEXT: local.get  )
 ;; NOOPT-NEXT: )
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT: $x()unreachable
 ;; NOOPT-NEXT: )  
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; NOOPT-EMPTY:
 ;; NOOPT-NEXT:    (i31.get_s
 ;; NOOPT-NEXT:  )(
 ;; NOOPT-NEXT:    ref.cast ((ref i31)
 ;; NOOPT-NEXT:   (unreachablelocal.get )
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: $y)

 ;; NOOPT:      (func $caller (param $x i32) (result i32)
 ;; NOOPT-NEXT: (local $y (ref eq))
 ;; NOOPT-NEXT: (if
 ;; NOOPT-NEXT:  (local.get $x)
 ;; NOOPT-NEXT:  (then
 ;; NOOPT-NEXT:   (return
 ;; NOOPT-NEXT:    (i32.const 1)
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: (local.set $y
 ;; NOOPT-NEXT:  (block
 ;; NOOPT-NEXT:   (drop
 ;; NOOPT-NEXT:    (call $throws
 ;; NOOPT-NEXT:     (local.get $x)
 ;; NOOPT-NEXT:    )
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:   (unreachable)
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: (i31.get_s
 ;; NOOPT-NEXT:  (ref.cast (ref i31)
 ;; NOOPT-NEXT:   (local.get $y)
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: )

 ;; NOOPT:      (type $0 (func))

 ;; NOOPT:      (type $1 (func (result i32)))

 ;; NOOPT:      (type $2 (func (param i32)))

 ;; NOOPT:      (type $3 (func (param i32) (result i32)))

 ;; NOOPT:      (tag $exn (type $2) (param i32))
 ;; CHECK:      (func $(ref.is_nullcall-loopspost
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: 1 (func post
 ;; CHECK-NEXT:  (resultpost
 ;; CHECK-NEXT: $(func $call-traps  ()((block
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (call $i32externfunc 
 ;; CHECK-NEXT:   )))
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT:   $call-tuple
 ;; CHECK-NEXT: result call-func  ( ref.is_null()i32)) 
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT:   (result  (block
 ;; CHECK-NEXT:   ( i32)
 ;; CHECK-NEXT: (unreachable(resultref.is_null
 ;; CHECK-NEXT:   i32)
 ;; CHECK-NEXT: (ref.is_null
 ;; CHECK-NEXT: (tuple.extract )2
 ;; CHECK-NEXT: 0
 ;; CHECK-NEXT:    (block
 ;; CHECK-NEXT:  ((  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )
 ;; CHECK-EMPTY:
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: dropblock
 ;; CHECK-NEXT: ref.is_null
 ;; CHECK-NEXT:    (call $loops)
 ;; CHECK-NEXT:   )
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: (
 ;; CHECK-NEXT: drop
 ;; CHECK-NEXT:    (  call     (($funcunreachable)block
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: )     )
 ;; CHECK-NEXT: )(
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: tuple.drop 2
 ;; CHECK-NEXT:     (call $tuple)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    ((unreachable
 ;; CHECK-NEXT: drop)
 ;; CHECK-NEXT:        (call $traps)()
 ;; CHECK-NEXT:   (unreachable
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT:  local.set 
 ;; CHECK-NEXT:   ))
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: $y
 ;; CHECK-NEXT:  (call 
 ;; CHECK-NEXT: $)
 ;; CHECK-NEXT: )
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: throws
 ;; CHECK-NEXT:      )

 ;; CHECK:      (func $caller (param $x i32) (result i32)
 ;; CHECK-NEXT: (local $y (ref eq))
 ;; CHECK-NEXT: (if
 ;; CHECK-NEXT:  (local.get $x)
 ;; CHECK-NEXT:  (then
 ;; CHECK-NEXT:   (return
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: (local.set $y
 ;; CHECK-NEXT:  (block
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (call $throws
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: (i31.get_s
 ;; CHECK-NEXT:  (ref.cast (ref i31)
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )

 ;; CHECK:      (func $call-loops (result i32)
 ;; CHECK-NEXT: pre
 ;; CHECK-NEXT: pre
 ;; CHECK-NEXT: ((ref.is_nullpre
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT:  (func block
 ;; CHECK-NEXT:   pre
 ;; CHECK-NEXT: ((drop
 ;; CHECK-NEXT: $func $call-func    call-tuple(call   ((resultresult  i32(i32)
 ;; CHECK-NEXT: pre
 ;; CHECK-NEXT: $loops(()
 ;; CHECK-NEXT: func (ref.is_null)
 ;; CHECK-NEXT: $
 ;; CHECK-NEXT:   func call-traps ((   $ref.is_nullresult
 ;; CHECK-NEXT: func ()i32
 ;; CHECK-NEXT: )call-externtuple.extract  $(result   2(
 ;; CHECK-NEXT: unreachablecaller   ) i32
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: (0)(param   
 ;; CHECK-NEXT: ref.is_null 
 ;; CHECK-NEXT:  ((block
 ;; CHECK-NEXT: $   ref.is_null(x
 ;; CHECK-NEXT: (   drop 
 ;; CHECK-NEXT: ()block    i32block(
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT:   (
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT: drop)
 ;; CHECK-EMPTY:
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT:    call     post
 ;; CHECK-NEXT: $(
 ;; CHECK-NEXT: (call traps(   call (block
 ;; CHECK-NEXT:    ()$$extern)
 ;; CHECK-NEXT:   func functuple.drop ))$call-loops (result i32)
 ;; CHECK-NEXT: (ref.is_null
 ;; CHECK-NEXT:  (block
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (call $loops)
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: (result i32)
 ;; CHECK-NEXT: (local )$   
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )
 ;; CHECK-EMPTY:
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: 2   )
 ;; CHECK-NEXT:   y   
 ;; CHECK-NEXT: ((ref eq))
 ;; CHECK-NEXT: (if
 ;; CHECK-NEXT:  (local.get $x)unreachable   )(
 ;; CHECK-NEXT: )  unreachable
 ;; CHECK-NEXT: )
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: )    (unreachable)
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: )post
 ;; CHECK-EMPTY:
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: ()
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: )func $call-extern
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: (post
 ;; CHECK-NEXT: result (i32func $post
 ;; CHECK-NEXT: call-func) 
 ;; CHECK-NEXT:  (then(
 ;; CHECK-NEXT: func (   (returnref.is_null(
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: (  result i32)
 ;; CHECK-NEXT: $(call-traps (result (ref.is_nulli32block
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (call 
 ;; CHECK-NEXT: $extern)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:  )(
 ;; CHECK-NEXT: block  ()ref.is_null
 ;; CHECK-NEXT:  (block
 ;; CHECK-EMPTY:
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: (   (drop
 ;; CHECK-NEXT:    (call $func)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT: drop  )
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT:      (call )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: $
 ;; CHECK-NEXT: traps)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:  )i32
 ;; CHECK-NEXT: .const  )
 ;; CHECK-NEXT: )
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: (local.set $y
 ;; CHECK-NEXT:  (block
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (call $throws
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: (i31.get_s
 ;; CHECK-NEXT:  (ref.cast (ref i31)
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: post
 ;; CHECK-NEXT: (func $caller (param $x i32) (result i32)
 ;; CHECK-NEXT: (local $y (ref eq))
 ;; CHECK-NEXT: (if
 ;; CHECK-NEXT:  (local.get $x)
 ;; CHECK-NEXT:  (then
 ;; CHECK-NEXT:   (return
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: (local.set $y
 ;; CHECK-NEXT:  (block
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (call $throws
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: (i31.get_s
 ;; CHECK-NEXT:  (ref.cast (ref i31)
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT:     (call $tuple)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (unreachable)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )

 ;; CHECK:      (func $caller (param $x i32) (result i32)
 ;; CHECK-NEXT: (local $y (ref eq))
 ;; CHECK-NEXT: (if
 ;; CHECK-NEXT:  (local.get $x)
 ;; CHECK-NEXT:  (then
 ;; CHECK-NEXT:   (return
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: (local.set $y
 ;; CHECK-NEXT:  (block
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (call $throws
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: (i31.get_s
 ;; CHECK-NEXT:  (ref.cast (ref i31)
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )

 ;; CHECK:      (func $call-tuple (result i32)
 ;; CHECK-NEXT: (ref.is_null
 ;; CHECK-NEXT:  (tuple.extract 2 0
 ;; CHECK-NEXT:   (block
 ;; CHECK-NEXT:    (tuple.drop 2
 ;; CHECK-NEXT:     (call $tuple)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (unreachable)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )

 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $throws (param $x i32)
 ;; CHECK-NEXT: (throw $exn
 ;; CHECK-NEXT:  (local.get $x)
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )

 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $throws (param $x i32pre
 ;; CHECK-NEXT: )(@binaryen.noreturn)
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: ((func throw $loops$
 ;; CHECK-NEXT: exn 
 ;; CHECK-NEXT:  (local.get $x)
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: (loop $l
 ;; CHECK-NEXT:  (br $l)
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )

 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $loopspre
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: (@binaryen.noreturn )
 ;; CHECK-NEXT: (loop $l
 ;; CHECK-NEXT:  (br $(lfunc )
 ;; CHECK-NEXT: )$func
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: )
 ;; CHECK-EMPTY:
 ;; CHECK-NEXT: (unreachable)
 ;; CHECK-NEXT: )

 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $func
 ;; CHECK-NEXT: (unreachable)
 ;; CHECK-NEXT: )

 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $extern
 ;; CHECK-NEXT: pre
 ;; CHECK-NEXT: (@binaryen.noreturn)
 ;; CHECK-NEXT: ((func $trapsunreachable
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )(nop)
 ;; CHECK-NEXT: (unreachable)
 ;; CHECK-NEXT: )

 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $traps
 ;; CHECK-NEXT: (nop)
 ;; CHECK-NEXT: (unreachable)
 ;; CHECK-NEXT: )

 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $extern
 ;; CHECK-NEXT: (unreachable)
 ;; CHECK-NEXT: )

 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $tuple
 ;; CHECK-NEXT: (unreachable)
 ;; CHECK-NEXT: )

 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $tuple
 ;; CHECK-NEXT: (unreachable)
 ;; CHECK-NEXT: )

 ;; CHECK:      (type $0 (func))

 ;; CHECK:      (type $1 (func (result i32)))

 ;; CHECK:      (type $2 (func (param i32)))

 ;; CHECK:      (type $3 (func (param i32) (result i32)))

 ;; CHECK:      (tag $exn (type $2) (param i32))
 (tag $exn (param i32))

 ;; This function only throws.
 ;; NOOPT:      (export "caller" (func $caller))

 ;; NOOPT:      (export "call-traps" (func $call-traps))

 ;; NOOPT:      (export "call-loops" (func $call-loops))

 ;; NOOPT:      (export "call-func" (func $call-func))

 ;; NOOPT:      (export "call-extern" (func $call-extern))

 ;; NOOPT:      (export "call-tuple" (func $call-tuple))

 ;; NOOPT:      (@binaryen.noreturn)
 ;; NOOPT-NEXT: (func $throws (type $2) (param $x i32)
 ;; NOOPT-NEXT:  (throw $exn
 ;; NOOPT-NEXT:   (local.get $x)
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (export "call-traps" (func $call-traps))

 ;; CHECK:      (export "call-loops" (func $call-loops))

 ;; CHECK:      (export "call-func" (func $call-func))

 ;; CHECK:      (export "call-extern" (func $call-extern))

 ;; CHECK:      (export "call-tuple" (func $call-tuple))

 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $throws (type $2) (param $0 i32)
 ;; CHECK-NEXT:  (throw $exn
 ;; CHECK-NEXT:   (local.get $0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $throws (param $x i32) (result (ref eq))
  (throw $exn
   (local.get $x)
  )
 )

 ;; This function ends in an unreachable. With --dae-optimizing, it ends up
 ;; with no result at all: its result type is refined to (ref none), which lets
 ;; us optimize the caller $call-traps so that the call is dropped (see there),
 ;; and then the next iteration of DAE removes the result, as all calls to this
 ;; function are dropped. The same happens to $throws above and to $loops, $func
 ;; and $extern below.
 ;; NOOPT:      (@binaryen.noreturn)
 ;; NOOPT-NEXT: (func $traps (type $0)
 ;; NOOPT-NEXT:  (drop
 ;; NOOPT-NEXT:   (i32.const 42)
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT:  (unreachable)
 ;; NOOPT-NEXT: )
 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $traps (type $0)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $traps (result (ref null any))
  ;; With --dae-optimizing, this function is optimized again after its result
  ;; is removed, which removes this drop.
  (drop
   (i32.const 42)
  )
  (unreachable)
 )

 ;; This function loops forever.
 ;; NOOPT:      (@binaryen.noreturn)
 ;; NOOPT-NEXT: (func $loops (type $0)
 ;; NOOPT-NEXT:  (loop $l
 ;; NOOPT-NEXT:   (br $l)
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $loops (type $0)
 ;; CHECK-NEXT:  (loop $l
 ;; CHECK-NEXT:   (br $l)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $loops (result anyref)
  (loop $l
   (br $l)
  )
 )

 ;; Other hierarchies.
 ;; NOOPT:      (@binaryen.noreturn)
 ;; NOOPT-NEXT: (func $func (type $0)
 ;; NOOPT-NEXT:  (unreachable)
 ;; NOOPT-NEXT: )
 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $func (type $0)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $func (result (ref null func))
  (unreachable)
 )

 ;; NOOPT:      (@binaryen.noreturn)
 ;; NOOPT-NEXT: (func $extern (type $0)
 ;; NOOPT-NEXT:  (unreachable)
 ;; NOOPT-NEXT: )
 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $extern (type $0)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $extern (result externref)
  (unreachable)
 )

 ;; Multivalue results are left alone.
 ;; NOOPT:      (@binaryen.noreturn)
 ;; NOOPT-NEXT: (func $tuple (type $0)
 ;; NOOPT-NEXT:  (unreachable)
 ;; NOOPT-NEXT: )
 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $tuple (type $0)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $tuple (result anyref anyref)
  (unreachable)
 )

 ;; NOOPT:      (func $caller (type $3) (param $x i32) (result i32)
 ;; NOOPT-NEXT:  (local $y (ref eq))
 ;; NOOPT-NEXT:  (if
 ;; NOOPT-NEXT:   (local.get $x)
 ;; NOOPT-NEXT:   (then
 ;; NOOPT-NEXT:    (return
 ;; NOOPT-NEXT:     (i32.const 1)
 ;; NOOPT-NEXT:    )
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT:  (local.set $y
 ;; NOOPT-NEXT:   (block
 ;; NOOPT-NEXT:    (call $throws
 ;; NOOPT-NEXT:     (local.get $x)
 ;; NOOPT-NEXT:    )
 ;; NOOPT-NEXT:    (unreachable)
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT:  (i31.get_s
 ;; NOOPT-NEXT:   (ref.cast (ref i31)
 ;; NOOPT-NEXT:    (local.get $y)
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; CHECK:      (func $caller (type $3) (param $0 i32) (result i32)
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (local.get $0)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (return
 ;; CHECK-NEXT:     (i32.const 1)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call $throws
 ;; CHECK-NEXT:   (local.get $0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $caller (export "caller") (param $x i32) (result i32)
  (local $y (ref eq))
  (if
   (local.get $x)
   (then
    (return
     (i32.const 1)
    )
   )
  )
  ;; With --dae-optimizing, as this call never returns, the code after it
  ;; becomes unreachable and is removed, together with the local. The call
  ;; itself is dropped, which then lets DAE remove the result of $throws.
  (local.set $y
   (call $throws
    (local.get $x)
   )
  )
  (i31.get_s
   (ref.cast (ref i31)
    (local.get $y)
   )
  )
 )

 ;; Each of the other functions is called from a separate function.
 ;; NOOPT:      (func $call-traps (type $1) (result i32)
 ;; NOOPT-NEXT:  (ref.is_null
 ;; NOOPT-NEXT:   (block
 ;; NOOPT-NEXT:    (call $traps)
 ;; NOOPT-NEXT:    (unreachable)
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; CHECK:      (func $call-traps (type $1) (result i32)
 ;; CHECK-NEXT:  (call $traps)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $call-traps (export "call-traps") (result i32)
  ;; With --dae-optimizing, as the call never returns, the ref.is_null is
  ;; replaced with an unreachable, and the call is dropped. The same happens in
  ;; the functions below, except $call-tuple.
  (ref.is_null
   (call $traps)
  )
 )

 ;; NOOPT:      (func $call-loops (type $1) (result i32)
 ;; NOOPT-NEXT:  (ref.is_null
 ;; NOOPT-NEXT:   (block
 ;; NOOPT-NEXT:    (call $loops)
 ;; NOOPT-NEXT:    (unreachable)
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; CHECK:      (func $call-loops (type $1) (result i32)
 ;; CHECK-NEXT:  (call $loops)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $call-loops (export "call-loops") (result i32)
  (ref.is_null
   (call $loops)
  )
 )

 ;; NOOPT:      (func $call-func (type $1) (result i32)
 ;; NOOPT-NEXT:  (ref.is_null
 ;; NOOPT-NEXT:   (block
 ;; NOOPT-NEXT:    (call $func)
 ;; NOOPT-NEXT:    (unreachable)
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; CHECK:      (func $call-func (type $1) (result i32)
 ;; CHECK-NEXT:  (call $func)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $call-func (export "call-func") (result i32)
  (ref.is_null
   (call $func)
  )
 )

 ;; NOOPT:      (func $call-extern (type $1) (result i32)
 ;; NOOPT-NEXT:  (ref.is_null
 ;; NOOPT-NEXT:   (block
 ;; NOOPT-NEXT:    (call $extern)
 ;; NOOPT-NEXT:    (unreachable)
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; CHECK:      (func $call-extern (type $1) (result i32)
 ;; CHECK-NEXT:  (call $extern)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $call-extern (export "call-extern") (result i32)
  (ref.is_null
   (call $extern)
  )
 )

 ;; NOOPT:      (func $call-tuple (type $1) (result i32)
 ;; NOOPT-NEXT:  (ref.is_null
 ;; NOOPT-NEXT:   (tuple.extract 2 0
 ;; NOOPT-NEXT:    (block
 ;; NOOPT-NEXT:     (call $tuple)
 ;; NOOPT-NEXT:     (unreachable)
 ;; NOOPT-NEXT:    )
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; CHECK:      (func $call-tuple (type $1) (result i32)
 ;; CHECK-NEXT:  (call $tuple)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $call-tuple (export "call-tuple") (result i32)
  (ref.is_null
   (tuple.extract 2 0
    (call $tuple)
   )
  )
 )
)

;; A chain of tail calls: $gV only throws, $e2 either returns an i31 or
;; tail-calls $gV, and $kG either returns an i31 or tail-calls $e2. $gV is
;; refined to (ref none), and then $e2 and $kG to (ref i31).
(module
 ;; NOOPT:      (func $e2 (param $0 i32) (result (ref eq))
 ;; NOOPT-NEXT: (if
 ;; NOOPT-NEXT:  (local.get $0)
 ;; NOOPT-NEXT:  (then
 ;; NOOPT-NEXT:   (return
 ;; NOOPT-NEXT:    (ref.i31
 ;; NOOPT-NEXT:     (i32.const 0)
 ;; NOOPT-NEXT:    )
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; NOOPT-NEXT: (return_call $gV)
 ;; NOOPT-NEXT: )

 ;; NOOPT:      (type $0 (func (result (ref eq))))

 ;; NOOPT:      (type $1 (func (param i32) (result (ref eq))))

 ;; NOOPT:      (type $2 (func (param (ref eq))))

 ;; NOOPT:      (type $3 (func (param i32) (result i32)))

 ;; NOOPT:      (global $msg (ref eq) (ref.i31
 ;; NOOPT-NEXT:  (i32.const 7)
 ;; NOOPT-NEXT: ))

 ;; NOOPT:      (tag $exn (type $2) (param (ref eq)))
 ;; CHECK:      (func $only-tail (result (ref eq))
 ;; CHECK-NEXT: i32(.const return_call $gV)
 ;; CHECK-NEXT: )

 ;; CHECK:      (func $e2 (param $0 i32) (result (ref eq))
 ;; CHECK-NEXT: (if
 ;; CHECK-NEXT:  (local.get $0)
 ;; CHECK-NEXT:  (then
 ;; CHECK-NEXT:   (return
 ;; CHECK-NEXT:    (ref.i31
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: (return_call $gV)
 ;; CHECK-NEXT: )

 ;; CHECK:      (func $only-tail (result (ref eq))
 ;; CHECK-NEXT: (return_call $gV)
 ;; CHECK-NEXT: )

 ;; CHECK:      (func $only-tail (result (ref eq))
 ;; CHECK-NEXT: (return_call $gV)
 ;; CHECK-NEXT: )

 ;; CHECK:      (func $e2 (param $0 i32) (result (ref eq))
 ;; CHECK-NEXT: (if
 ;; CHECK-NEXT:  (local.get $0)
 ;; CHECK-NEXT:  (then
 ;; CHECK-NEXT:   (return
 ;; CHECK-NEXT:    (ref.i31
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: (return_call $gV)
 ;; CHECK-NEXT: )

 ;; CHECK:      (func $e2 (param $0 i32) (result (ref eq))
 ;; CHECK-NEXT: (if
 ;; CHECK-NEXT:  (local.get $0)
 ;; CHECK-NEXT:  (then
 ;; CHECK-NEXT:   (return
 ;; CHECK-NEXT:    (ref.i31
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: (return_call $gV)
 ;; CHECK-NEXT: )

 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $gV (result (ref eq))
 ;; CHECK-NEXT: (local $0 (ref eq))
 ;; CHECK-NEXT: (local.set $0
 ;; CHECK-NEXT:  (global.get $msg)
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: (throw $exn
 ;; CHECK-NEXT:  (local.get $0)
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )

 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $gV (result (ref eq))
 ;; CHECK-NEXT: (local $0 (ref eq))
 ;; CHECK-NEXT: (local.set $0
 ;; CHECK-NEXT:  (global.get $msg)
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: (throw $exn
 ;; CHECK-NEXT:  (local.get $0)
 ;; CHECK-NEXT: )
 ;; CHECK-NEXT: )

 ;; CHECK:      (type $0 (func (result (ref eq))))

 ;; CHECK:      (type $1 (func (param i32) (result (ref eq))))

 ;; CHECK:      (type $2 (func (param (ref eq))))

 ;; CHECK:      (type $3 (func (param i32) (result i32)))

 ;; CHECK:      (global $msg (ref eq) (ref.i31
 ;; CHECK-NEXT:  (i32.const 7)
 ;; CHECK-NEXT: ))

 ;; CHECK:      (tag $exn (type $2) (param (ref eq)))
 (tag $exn (param (ref eq)))

 (global $msg (ref eq) (ref.i31 (i32.const 7)))

 ;; NOOPT:      (export "user" (func $user))

 ;; NOOPT:      (@binaryen.noreturn)
 ;; NOOPT-NEXT: (func $gV (type $0) (result (ref eq))
 ;; NOOPT-NEXT:  (local $0 (ref eq))
 ;; NOOPT-NEXT:  (local.set $0
 ;; NOOPT-NEXT:   (global.get $msg)
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT:  (throw $exn
 ;; NOOPT-NEXT:   (local.get $0)
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; CHECK:      (export "user" (func $user))

 ;; CHECK:      (@binaryen.noreturn)
 ;; CHECK-NEXT: (func $gV (type $0) (result (ref eq))
 ;; CHECK-NEXT:  (throw $exn
 ;; CHECK-NEXT:   (global.get $msg)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $gV (param $0 (ref eq)) (result (ref eq))
  (throw $exn
   (local.get $0)
  )
 )

 ;; NOOPT:      (func $e2 (type $1) (param $0 i32) (result (ref eq))
 ;; NOOPT-NEXT:  (if
 ;; NOOPT-NEXT:   (local.get $0)
 ;; NOOPT-NEXT:   (then
 ;; NOOPT-NEXT:    (return
 ;; NOOPT-NEXT:     (ref.i31
 ;; NOOPT-NEXT:      (i32.const 0)
 ;; NOOPT-NEXT:     )
 ;; NOOPT-NEXT:    )
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT:  (return_call $gV)
 ;; NOOPT-NEXT: )
 ;; CHECK:      (func $e2 (type $1) (param $0 i32) (result (ref eq))
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (local.get $0)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (return
 ;; CHECK-NEXT:     (ref.i31
 ;; CHECK-NEXT:      (i32.const 0)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (return_call $gV)
 ;; CHECK-NEXT: )
 (func $e2 (param $0 i32) (result (ref eq))
  (if
   (local.get $0)
   (then
    (return
     (ref.i31
      (i32.const 0)
     )
    )
   )
  )
  (return_call $gV
   (global.get $msg)
  )
 )

 ;; NOOPT:      (func $kG (type $1) (param $0 i32) (result (ref eq))
 ;; NOOPT-NEXT:  (if
 ;; NOOPT-NEXT:   (i32.eqz
 ;; NOOPT-NEXT:    (local.get $0)
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:   (then
 ;; NOOPT-NEXT:    (return
 ;; NOOPT-NEXT:     (ref.i31
 ;; NOOPT-NEXT:      (i32.const 1)
 ;; NOOPT-NEXT:     )
 ;; NOOPT-NEXT:    )
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT:  (return_call $e2
 ;; NOOPT-NEXT:   (local.get $0)
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; CHECK:      (func $kG (type $1) (param $0 i32) (result (ref eq))
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.eqz
 ;; CHECK-NEXT:    (local.get $0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (return
 ;; CHECK-NEXT:     (ref.i31
 ;; CHECK-NEXT:      (i32.const 1)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (return_call $e2
 ;; CHECK-NEXT:   (local.get $0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $kG (param $0 i32) (result (ref eq))
  (if
   (i32.eqz
    (local.get $0)
   )
   (then
    (return
     (ref.i31
      (i32.const 1)
     )
    )
   )
  )
  (return_call $e2
   (local.get $0)
  )
 )

 ;; This function only tail-calls $gV, so it is refined to (ref none) as well.
 ;; NOOPT:      (func $only-tail (type $0) (result (ref eq))
 ;; NOOPT-NEXT:  (return_call $gV)
 ;; NOOPT-NEXT: )
 ;; CHECK:      (func $only-tail (type $0) (result (ref eq))
 ;; CHECK-NEXT:  (return_call $gV)
 ;; CHECK-NEXT: )
 (func $only-tail (result (ref eq))
  (return_call $gV
   (global.get $msg)
  )
 )

 ;; With --dae-optimizing, this function is optimized once the results of the
 ;; functions it calls are refined.
 ;; NOOPT:      (func $user (type $3) (param $0 i32) (result i32)
 ;; NOOPT-NEXT:  (i32.add
 ;; NOOPT-NEXT:   (i31.get_s
 ;; NOOPT-NEXT:    (ref.cast (ref i31)
 ;; NOOPT-NEXT:     (call $kG
 ;; NOOPT-NEXT:      (local.get $0)
 ;; NOOPT-NEXT:     )
 ;; NOOPT-NEXT:    )
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:   (i31.get_s
 ;; NOOPT-NEXT:    (ref.cast (ref i31)
 ;; NOOPT-NEXT:     (call $only-tail)
 ;; NOOPT-NEXT:    )
 ;; NOOPT-NEXT:   )
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT: )
 ;; CHECK:      (func $user (type $3) (param $0 i32) (result i32)
 ;; CHECK-NEXT:  (i32.add
 ;; CHECK-NEXT:   (i31.get_s
 ;; CHECK-NEXT:    (ref.cast (ref i31)
 ;; CHECK-NEXT:     (call $kG
 ;; CHECK-NEXT:      (local.get $0)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (i31.get_s
 ;; CHECK-NEXT:    (ref.cast (ref i31)
 ;; CHECK-NEXT:     (call $only-tail)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $user (export "user") (param $0 i32) (result i32)
  (i32.add
   (i31.get_s
    ;; This cast is removed, as $kG is now known to return a (ref i31).
    (ref.cast (ref i31)
     (call $kG
      (local.get $0)
     )
    )
   )
   (i31.get_s
    ;; As $only-tail now returns a (ref none), this cast is refinalized to a
    ;; cast to (ref none), as we see with --dae. Such a cast can never succeed,
    ;; so optimize-instructions replaces it with a block that drops the call
    ;; and then traps. merge-blocks then moves that block out of the
    ;; i31.get_s, which leaves (i31.get_s (unreachable)). No dce runs after
    ;; merge-blocks in the pipeline, so this is not cleaned up further. (Unlike
    ;; for the functions in the previous module, the result of $only-tail
    ;; cannot be removed, as that function contains a tail call.)
    (ref.cast (ref i31)
     (call $only-tail)
    )
   )
  )
 )
)

;; Negative cases: functions that are exported or referenced cannot be
;; refined, as we do not see all their calls.
(module
 ;; NOOPT:      (type $0 (func (result (ref eq))))

 ;; NOOPT:      (type $1 (func (result (ref func))))

 ;; NOOPT:      (elem declare func $referenced)
 ;; CHECK:      (type $0 (func (result (ref eq))))

 ;; CHECK:      (type $1 (func (result (ref func))))

 ;; CHECK:      (elem declare func $referenced)
 (elem declare func $referenced)

 ;; NOOPT:      (export "exported" (func $exported))

 ;; NOOPT:      (export "user" (func $user))

 ;; NOOPT:      (func $exported (type $0) (result (ref eq))
 ;; NOOPT-NEXT:  (unreachable)
 ;; NOOPT-NEXT: )
 ;; CHECK:      (export "exported" (func $exported))

 ;; CHECK:      (export "user" (func $user))

 ;; CHECK:      (func $exported (type $0) (result (ref eq))
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $exported (export "exported") (result (ref eq))
  (unreachable)
 )

 ;; NOOPT:      (func $referenced (type $0) (result (ref eq))
 ;; NOOPT-NEXT:  (unreachable)
 ;; NOOPT-NEXT: )
 ;; CHECK:      (func $referenced (type $0) (result (ref eq))
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $referenced (result (ref eq))
  (unreachable)
 )

 ;; NOOPT:      (func $user (type $1) (result (ref func))
 ;; NOOPT-NEXT:  (drop
 ;; NOOPT-NEXT:   (call $exported)
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT:  (drop
 ;; NOOPT-NEXT:   (call $referenced)
 ;; NOOPT-NEXT:  )
 ;; NOOPT-NEXT:  (ref.func $referenced)
 ;; NOOPT-NEXT: )
 ;; CHECK:      (func $user (type $1) (result (ref func))
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $exported)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $referenced)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (ref.func $referenced)
 ;; CHECK-NEXT: )
 (func $user (export "user") (result (ref func))
  (drop
   (call $exported)
  )
  (drop
   (call $referenced)
  )
  (ref.func $referenced)
 )
)
