;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; Verify that normally we do *not* add noreturn annotations to the module.
;; DAE uses them internally, then cleans them up (so users do not need to strip
;; them afterwards). Only when the right flag is used, are they kept.

;; RUN: foreach %s %t wasm-opt --dae                              all -S -o - | filecheck %s --check-prefix=NORM
;; RUN: foreach %s %t wasm-opt --dae --pass-arg=dae-keep-noreturn all -S -o - | filecheck %s --check-prefix=KEEP
;; RUN: foreach %s %t wasm-opt -O3                                -all -S -o - | filecheck %s --check-prefix=_O3_

(module
 (func $i32-noreturn (export "i32-noreturn") (result i32)
  ;; The i32 type is MVP and cannot be refined like GC types, but we can still
  ;; infer this is noreturn.
  (unreachable)
 )

 ;; CHECK:      (func $call-i32-noreturn (export "call-i32-noreturn") (type $0)
 ;; CHECK-NEXT:  (call $i32-noreturn)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $call-i32-noreturn (export "call-i32-noreturn")
  ;; An unreachable will appear after this call.
  (drop
   (call $i32-noreturn)
  )
 )

