;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; Verify that normally we do *not* add noreturn annotations to the module.
;; DAE uses them internally, then cleans them up (so users do not need to strip
;; them afterwards). Only when the right flag is used, are they kept.

;; RUN: foreach %s %t wasm-opt --dae                              -all -S -o - | filecheck %s --check-prefix=NORM
;; RUN: foreach %s %t wasm-opt --dae --pass-arg=dae-keep-noreturn -all -S -o - | filecheck %s --check-prefix=KEEP
;; RUN: foreach %s %t wasm-opt -O3                                -all -S -o - | filecheck %s --check-prefix=O3__

(module
 ;; NORM:      (type $0 (func (result i32)))

 ;; NORM:      (type $1 (func))

 ;; NORM:      (export "i32-noreturn" (func $i32-noreturn))

 ;; NORM:      (export "call-i32-noreturn" (func $call-i32-noreturn))

 ;; NORM:      (func $i32-noreturn (type $0) (result i32)
 ;; NORM-NEXT:  (unreachable)
 ;; NORM-NEXT: )
 ;; KEEP:      (type $0 (func (result i32)))

 ;; KEEP:      (type $1 (func))

 ;; KEEP:      (export "i32-noreturn" (func $i32-noreturn))

 ;; KEEP:      (export "call-i32-noreturn" (func $call-i32-noreturn))

 ;; KEEP:      (func $i32-noreturn (type $0) (result i32)
 ;; KEEP-NEXT:  (unreachable)
 ;; KEEP-NEXT: )
 ;; O3__:      (type $0 (func (result i32)))

 ;; O3__:      (type $1 (func))

 ;; O3__:      (export "i32-noreturn" (func $i32-noreturn))

 ;; O3__:      (export "call-i32-noreturn" (func $call-i32-noreturn))

 ;; O3__:      (func $i32-noreturn (type $0) (result i32)
 ;; O3__-NEXT:  (unreachable)
 ;; O3__-NEXT: )
 (func $i32-noreturn (export "i32-noreturn") (result i32)
  ;; The i32 type is MVP and cannot be refined like GC types, but we can still
  ;; infer this is noreturn.
  (unreachable)
 )

 ;; CHECK:      (func $call-i32-noreturn (export "call-i32-noreturn") (type $0)
 ;; CHECK-NEXT:  (call $i32-noreturn)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 ;; NORM:      (func $call-i32-noreturn (type $1)
 ;; NORM-NEXT:  (drop
 ;; NORM-NEXT:   (call $i32-noreturn)
 ;; NORM-NEXT:  )
 ;; NORM-NEXT: )
 ;; KEEP:      (func $call-i32-noreturn (type $1)
 ;; KEEP-NEXT:  (drop
 ;; KEEP-NEXT:   (call $i32-noreturn)
 ;; KEEP-NEXT:  )
 ;; KEEP-NEXT: )
 ;; O3__:      (func $call-i32-noreturn (type $1)
 ;; O3__-NEXT:  (unreachable)
 ;; O3__-NEXT: )
 (func $call-i32-noreturn (export "call-i32-noreturn")
  ;; An unreachable will appear after this call.
  (drop
   (call $i32-noreturn)
  )
 )
)
