;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --directize -all -S -o - | filecheck %s

;; Test that we process constant operations in the start function.

;; Write to an index in the table from the start function. We can optimize as if
;; it were set in an element segment.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (export "trapper" (func $trapper))

 ;; CHECK:      (export "trapper-2" (func $trapper-2))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $table
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $table
   (i32.const 1)
   (ref.func $target)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call $target)
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; This turns into a direct call.
  (call_indirect (type $func)
   (i32.const 1)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )

 ;; CHECK:      (func $trapper (type $func)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $trapper (export "trapper")
  ;; This index has nothing and will trap.
  (call_indirect (type $func)
   (i32.const 0)
  )
 )

 ;; CHECK:      (func $trapper-2 (type $func)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $trapper-2 (export "trapper-2")
  ;; Ditto.
  (call_indirect (type $func)
   (i32.const 2)
  )
 )
)

;; As above, but the table.set index is not constant.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $table
 ;; CHECK-NEXT:   (i32.add
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $table
   ;; This add is not identified as a constant.
   (i32.add
    (i32.const 1)
    (i32.const 0)
   )
   (ref.func $target)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call_indirect $table (type $func)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; This cannot be optimized.
  (call_indirect (type $func)
   (i32.const 1)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )
)

;; As above, but now the value is non-constant.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $table
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (select (result (ref (exact $func)))
 ;; CHECK-NEXT:    (ref.func $target)
 ;; CHECK-NEXT:    (ref.func $target)
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $table
   (i32.const 1)
   ;; This select is not identified as constant.
   (select
    (ref.func $target)
    (ref.func $target)
    (i32.const 1)
   )
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call_indirect $table (type $func)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; This cannot be optimized.
  (call_indirect (type $func)
   (i32.const 1)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )
)

;; table.fill instead of table.set.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (export "trapper" (func $trapper))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.fill $table
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:   (i32.const 2)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  ;; This fills in two slots.
  (table.fill $table
   (i32.const 1)
   (ref.func $target)
   (i32.const 2)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call $target)
 ;; CHECK-NEXT:  (call $target)
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; Both of these get optimized.
  (call_indirect (type $func)
   (i32.const 1)
  )
  (call_indirect (type $func)
   (i32.const 2)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )

 ;; CHECK:      (func $trapper (type $func)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $trapper (export "trapper")
  ;; This traps.
  (call_indirect (type $func)
   (i32.const 3)
  )
 )
)
