;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --directize -all -S -o - | filecheck %s

;; Test that we process constant operations in the start function.

;; Write to an index in the table from the start function. We can optimize as if
;; it were set in an element segment.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $table
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $table
   (i32.const 1)
   (ref.func $target)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call $target)
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; This turns into a direct call.
  (call_indirect (type $func)
   (i32.const 1)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target)
 )

 (func $trapper (export "trapper")
  ;; This index has nothing and will trap.
  (call_indirect (type $func)
   (i32.const 3)
  )
 )
)

