;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --directize -all -S -o - | filecheck %s

;; Test that we process constant operations in the start function.

;; Write to an index in the table from the start function. We can optimize as if
;; it were set in an element segment.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (export "trapper" (func $trapper))

 ;; CHECK:      (export "trapper-2" (func $trapper-2))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $table
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $table
   (i32.const 1)
   (ref.func $target)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call $target)
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; This turns into a direct call.
  (call_indirect (type $func)
   (i32.const 1)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )

 ;; CHECK:      (func $trapper (type $func)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $trapper (export "trapper")
  ;; This index has nothing and will trap.
  (call_indirect (type $func)
   (i32.const 0)
  )
 )

 ;; CHECK:      (func $trapper-2 (type $func)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $trapper-2 (export "trapper-2")
  ;; Ditto.
  (call_indirect (type $func)
   (i32.const 2)
  )
 )
)

;; As above, but the table.set index is not constant.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $table
 ;; CHECK-NEXT:   (i32.add
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $table
   ;; This add is not identified as a constant.
   (i32.add
    (i32.const 1)
    (i32.const 0)
   )
   (ref.func $target)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call_indirect $table (type $func)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; This cannot be optimized.
  (call_indirect (type $func)
   (i32.const 1)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )
)

;; As above, but now the value is non-constant.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $table
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (select (result (ref (exact $func)))
 ;; CHECK-NEXT:    (ref.func $target)
 ;; CHECK-NEXT:    (ref.func $target)
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $table
   (i32.const 1)
   ;; This select is not identified as constant.
   (select
    (ref.func $target)
    (ref.func $target)
    (i32.const 1)
   )
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call_indirect $table (type $func)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; This cannot be optimized.
  (call_indirect (type $func)
   (i32.const 1)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )
)

;; table.fill instead of table.set.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (export "trapper" (func $trapper))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.fill $table
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:   (i32.const 2)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  ;; This fills in two slots.
  (table.fill $table
   (i32.const 1)
   (ref.func $target)
   (i32.const 2)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call $target)
 ;; CHECK-NEXT:  (call $target)
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; Both of these get optimized.
  (call_indirect (type $func)
   (i32.const 1)
  )
  (call_indirect (type $func)
   (i32.const 2)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )

 ;; CHECK:      (func $trapper (type $func)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $trapper (export "trapper")
  ;; This traps.
  (call_indirect (type $func)
   (i32.const 3)
  )
 )
)

;; As the last, but the size is not constant.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.fill $table
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:   (i32.add
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.fill $table
   (i32.const 1)
   (ref.func $target)
   ;; This add is not identified as a constant.
   (i32.add
    (i32.const 1)
    (i32.const 1)
   )
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call_indirect $table (type $func)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call_indirect $table (type $func)
 ;; CHECK-NEXT:   (i32.const 2)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; Nothing here is optimized.
  (call_indirect (type $func)
   (i32.const 1)
  )
  (call_indirect (type $func)
   (i32.const 2)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )
)

;; We do not optimize non-function values, but also do not error.
(module
 ;; CHECK:      (type $0 (func))

 ;; CHECK:      (type $struct (struct))
 (type $struct (struct))

 ;; CHECK:      (table $table 5 anyref)
 (table $table 5 anyref)

 ;; CHECK:      (export "getter" (func $getter))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $0)
 ;; CHECK-NEXT:  (table.set $table
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (struct.new_default $struct)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $table
   (i32.const 1)
   (struct.new $struct)
  )
 )

 ;; CHECK:      (func $getter (type $0)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (table.get $table
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $getter (export "getter")
  (drop
   (table.get $table
    (i32.const 1)
   )
  )
 )
)

;; table.set out of bounds.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $table
 ;; CHECK-NEXT:   (i32.const 5)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  ;; The table is size 5, we write to index 5, which is too much. This traps at
  ;; runtime and we don't do anything at compile time.
  (table.set $table
   (i32.const 5)
   (ref.func $target)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call_indirect $table (type $func)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  (call_indirect (type $func)
   (i32.const 1)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )
)

;; table.fill with an overflow is not optimized.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.fill $table
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:   (i32.const -1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.fill $table
   (i32.const 1)
   (ref.func $target)
   ;; Huge unsigned value.
   (i32.const -1)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call_indirect $table (type $func)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call_indirect $table (type $func)
 ;; CHECK-NEXT:   (i32.const 2)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; We do not optimize here.
  (call_indirect (type $func)
   (i32.const 1)
  )
  (call_indirect (type $func)
   (i32.const 2)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )
)

;; Two sets in the start.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target $target-b)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (export "trapper" (func $trapper))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $table
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (nop)
 ;; CHECK-NEXT:  (table.set $table
 ;; CHECK-NEXT:   (i32.const 3)
 ;; CHECK-NEXT:   (ref.func $target-b)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $table
   (i32.const 1)
   (ref.func $target)
  )
  (nop) ;; this does not bother us
  (table.set $table
   (i32.const 3)
   (ref.func $target-b)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call $target)
 ;; CHECK-NEXT:  (call $target-b)
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; Both of these get optimized.
  (call_indirect (type $func)
   (i32.const 1)
  )
  (call_indirect (type $func)
   (i32.const 3)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )

 ;; CHECK:      (func $target-b (type $func)
 ;; CHECK-NEXT: )
 (func $target-b
 )

 ;; CHECK:      (func $trapper (type $func)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $trapper (export "trapper")
  ;; This index in the middle remains unset, and will trap.
  (call_indirect (type $func)
   (i32.const 2)
  )
 )
)

;; Two sets for different tables.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $a 5 funcref)
 (table $a 5 funcref)

 ;; CHECK:      (table $b 5 funcref)
 (table $b 5 funcref)

 ;; CHECK:      (elem declare func $target $target-b)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $a
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (nop)
 ;; CHECK-NEXT:  (table.set $b
 ;; CHECK-NEXT:   (i32.const 3)
 ;; CHECK-NEXT:   (ref.func $target-b)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $a
   (i32.const 1)
   (ref.func $target)
  )
  (nop) ;; this does not bother us
  (table.set $b
   (i32.const 3)
   (ref.func $target-b)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call $target)
 ;; CHECK-NEXT:  (call $target-b)
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; Both of these get optimized.
  (call_indirect $a (type $func)
   (i32.const 1)
  )
  (call_indirect $b (type $func)
   (i32.const 3)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )

 ;; CHECK:      (func $target-b (type $func)
 ;; CHECK-NEXT: )
 (func $target-b
 )
)

;; Two sets for different tables, with a call in the middle.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $a 5 funcref)
 (table $a 5 funcref)

 ;; CHECK:      (table $b 5 funcref)
 (table $b 5 funcref)

 ;; CHECK:      (elem declare func $target $target-b)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $a
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call $caller)
 ;; CHECK-NEXT:  (table.set $b
 ;; CHECK-NEXT:   (i32.const 3)
 ;; CHECK-NEXT:   (ref.func $target-b)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $a
   (i32.const 1)
   (ref.func $target)
  )
  (call $caller) ;; this stops us from optimizing anything further
  (table.set $b
   (i32.const 3)
   (ref.func $target-b)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call $target)
 ;; CHECK-NEXT:  (call_indirect $b (type $func)
 ;; CHECK-NEXT:   (i32.const 3)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; Only the first gets optimized.
  (call_indirect $a (type $func)
   (i32.const 1)
  )
  (call_indirect $b (type $func)
   (i32.const 3)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )

 ;; CHECK:      (func $target-b (type $func)
 ;; CHECK-NEXT: )
 (func $target-b
 )
)

;; Three sets.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $a 5 funcref)
 (table $a 5 funcref)

 ;; CHECK:      (table $b 5 funcref)
 (table $b 5 funcref)

 ;; CHECK:      (elem declare func $target $target-b)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $a
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call $caller)
 ;; CHECK-NEXT:  (table.set $a
 ;; CHECK-NEXT:   (i32.const 2)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (table.set $b
 ;; CHECK-NEXT:   (i32.const 3)
 ;; CHECK-NEXT:   (ref.func $target-b)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $a
   (i32.const 1)
   (ref.func $target)
  )
  (call $caller)
  ;; After the call we now access table $a. This stops us from optimizing that
  ;; table entirely, as after the call, we assume the worst about the rest, and
  ;; in particular we don't know what is at index 2 (this write might or might
  ;; not happen). TODO: we could mark some indexes as "unknown" and still
  ;; optimize others.
  (table.set $a
   (i32.const 2)
   (ref.func $target)
  )
  (table.set $b
   (i32.const 3)
   (ref.func $target-b)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call_indirect $a (type $func)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call_indirect $b (type $func)
 ;; CHECK-NEXT:   (i32.const 3)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; Neither gets optimized.
  (call_indirect $a (type $func)
   (i32.const 1)
  )
  (call_indirect $b (type $func)
   (i32.const 3)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )

 ;; CHECK:      (func $target-b (type $func)
 ;; CHECK-NEXT: )
 (func $target-b
 )
)

;; Two sets with an unreachable in the middle.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $a 5 funcref)
 (table $a 5 funcref)

 ;; CHECK:      (table $b 5 funcref)
 (table $b 5 funcref)

 ;; CHECK:      (elem declare func $target $target-b)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $a
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT:  (table.set $b
 ;; CHECK-NEXT:   (i32.const 3)
 ;; CHECK-NEXT:   (ref.func $target-b)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $a
   (i32.const 1)
   (ref.func $target)
  )
  (unreachable) ;; this stops us from optimizing anything further
  (table.set $b
   (i32.const 3)
   (ref.func $target-b)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call $target)
 ;; CHECK-NEXT:  (call_indirect $b (type $func)
 ;; CHECK-NEXT:   (i32.const 3)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; Only the first gets optimized.
  (call_indirect $a (type $func)
   (i32.const 1)
  )
  (call_indirect $b (type $func)
   (i32.const 3)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )

 ;; CHECK:      (func $target-b (type $func)
 ;; CHECK-NEXT: )
 (func $target-b
 )
)

;; Two sets with a conditional return in the middle.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $a 5 funcref)
 (table $a 5 funcref)

 ;; CHECK:      (table $b 5 funcref)
 (table $b 5 funcref)

 ;; CHECK:      (elem declare func $target $target-b)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $a
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (return)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (table.set $b
 ;; CHECK-NEXT:   (i32.const 3)
 ;; CHECK-NEXT:   (ref.func $target-b)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $a
   (i32.const 1)
   (ref.func $target)
  )
  ;; This stops us from optimizing anything further.
  (if
   (i32.const 1)
   (then
    (return)
   )
  )
  (table.set $b
   (i32.const 3)
   (ref.func $target-b)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call $target)
 ;; CHECK-NEXT:  (call_indirect $b (type $func)
 ;; CHECK-NEXT:   (i32.const 3)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; Only the first gets optimized.
  (call_indirect $a (type $func)
   (i32.const 1)
  )
  (call_indirect $b (type $func)
   (i32.const 3)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )

 ;; CHECK:      (func $target-b (type $func)
 ;; CHECK-NEXT: )
 (func $target-b
 )
)

;; table.copy.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (table.set $table
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (table.copy $table $table
 ;; CHECK-NEXT:   (i32.const 0)
 ;; CHECK-NEXT:   (i32.const 0)
 ;; CHECK-NEXT:   (i32.const 0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  (table.set $table
   (i32.const 1)
   (ref.func $target)
  )
  ;; This stops us from optimizing this table. TODO: we could handle constant
  ;; cases like this.
  (table.copy $table $table
   (i32.const 0)
   (i32.const 0)
   (i32.const 0)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call_indirect $table (type $func)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  (call_indirect (type $func)
   (i32.const 1)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )
)

;; table.grow.
(module
 ;; CHECK:      (type $func (func))
 (type $func (func))

 ;; CHECK:      (table $table 5 funcref)
 (table $table 5 funcref)

 ;; CHECK:      (elem declare func $start $target)

 ;; CHECK:      (export "caller" (func $caller))

 ;; CHECK:      (start $start)
 (start $start)

 ;; CHECK:      (func $start (type $func)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (table.grow $table
 ;; CHECK-NEXT:    (ref.func $start)
 ;; CHECK-NEXT:    (i32.const 42)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (table.set $table
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (ref.func $target)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $start
  ;; This does not stop us from optimizing this table, as it just appends, even
  ;; though it happens before a set.
  ;; TODO: we could also handle constant cases like this, as we do table.fill.
  (drop
   (table.grow $table
    (ref.func $start)
    (i32.const 42)
   )
  )

  (table.set $table
   (i32.const 1)
   (ref.func $target)
  )
 )

 ;; CHECK:      (func $caller (type $func)
 ;; CHECK-NEXT:  (call $target)
 ;; CHECK-NEXT:  (call_indirect $table (type $func)
 ;; CHECK-NEXT:   (i32.const 10)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call_indirect $table (type $func)
 ;; CHECK-NEXT:   (i32.const 100)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $caller (export "caller")
  ;; This is in the elem segment, so we can optimize it.
  (call_indirect (type $func)
   (i32.const 1)
  )
  ;; This is in the range that we grow to. We could optimize this TODO
  (call_indirect (type $func)
   (i32.const 10)
  )
  ;; This is outside the grown range. We could optimize this to a trap TODO
  (call_indirect (type $func)
   (i32.const 100)
  )
 )

 ;; CHECK:      (func $target (type $func)
 ;; CHECK-NEXT: )
 (func $target
 )
)
