;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s --optimize-instructions -S -o - | filecheck %s

(module
 ;; CHECK:      (func $yes (param $x i32) (result i32)
 ;; CHECK-NEXT:  (i32.ge_u
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:   (i32.const 4000000)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $yes (param $x i32) (result i32)
  ;; Test conversions between signed and unsigned comparisons. Here we check if
  ;; x < 0 or x >= 4000000, but the comparisons are signed, so we are checking
  ;; if x >= 4000000 or the sign bit is set, which can be checked using a single
  ;; unsigned comparison.
  (i32.or
   (i32.lt_s
    (local.get $x)
    (i32.const 0)
   )
   (i32.ge_s
    (local.get $x)
    (i32.const 4000000)
   )
  )
 )

 ;; CHECK:      (func $yes-flipped (param $x i32) (result i32)
 ;; CHECK-NEXT:  (i32.ge_u
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:   (i32.const 4000000)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $yes-flipped (param $x i32) (result i32)
  ;; Ditto, but flipped. Also optimizable.
  (i32.or
   (i32.ge_s
    (local.get $x)
    (i32.const 4000000)
   )
   (i32.lt_s
    (local.get $x)
    (i32.const 0)
   )
  )
 )

 ;; CHECK:      (func $yes-tee (param $x i32) (result i32)
 ;; CHECK-NEXT:  (local $temp i32)
 ;; CHECK-NEXT:  (i32.ge_u
 ;; CHECK-NEXT:   (local.tee $temp
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (i32.const 4000000)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $yes-tee (param $x i32) (result i32)
  ;; Ditto, with a tee'd local, also optimizable.
  (local $temp i32)
  (i32.or
   (i32.lt_s
    (local.tee $temp
     (local.get $x)
    )
    (i32.const 0)
   )
   (i32.ge_s
    (local.get $temp)
    (i32.const 4000000)
   )
  )
 )

 ;; CHECK:      (func $yes-tee-flipped (param $x i32) (result i32)
 ;; CHECK-NEXT:  (local $temp i32)
 ;; CHECK-NEXT:  (i32.ge_u
 ;; CHECK-NEXT:   (local.tee $temp
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (i32.const 4000000)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $yes-tee-flipped (param $x i32) (result i32)
  ;; Ditto, with tee+flip.
  (local $temp i32)
  (i32.or
   (i32.ge_s
    (local.tee $temp
     (local.get $x)
    )
    (i32.const 4000000)
   )
   (i32.lt_s
    (local.get $temp)
    (i32.const 0)
   )
  )
 )

 ;; CHECK:      (func $no-unsigned (param $x i32) (result i32)
 ;; CHECK-NEXT:  (i32.ge_u
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:   (i32.const 4000000)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-unsigned (param $x i32) (result i32)
  ;; The comparisons are unsigned. We do not optimize for the above reasons, but
  ;; this is optimizable (< 0 is never true, when unsigned).
  (i32.or
   (i32.lt_u ;; this changed
    (local.get $x)
    (i32.const 0)
   )
   (i32.ge_u ;; this changed
    (local.get $x)
    (i32.const 4000000)
   )
  )
 )

 ;; CHECK:      (func $no-nonzero (param $x i32) (result i32)
 ;; CHECK-NEXT:  (i32.or
 ;; CHECK-NEXT:   (i32.lt_s
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:    (i32.const -1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (i32.ge_s
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:    (i32.const 4000000)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-nonzero (param $x i32) (result i32)
  ;; The < 0 is not < another constant. We do not optimize.
  (i32.or
   (i32.lt_s
    (local.get $x)
    (i32.const -1) ;; this changed
   )
   (i32.ge_s
    (local.get $x)
    (i32.const 4000000)
   )
  )
 )

 ;; CHECK:      (func $no-negative (param $x i32) (result i32)
 ;; CHECK-NEXT:  (i32.or
 ;; CHECK-NEXT:   (i32.lt_s
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (i32.ge_s
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:    (i32.const -1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-negative (param $x i32) (result i32)
  ;; The constant is not non-negative. We do not optimize for the above reaosns
  (i32.or
   (i32.lt_s
    (local.get $x)
    (i32.const 0)
   )
   (i32.ge_s
    (local.get $x)
    (i32.const -1) ;; this changed
   )
  )
 )

 ;; CHECK:      (func $no-different (param $x i32) (param $y i32) (result i32)
 ;; CHECK-NEXT:  (i32.or
 ;; CHECK-NEXT:   (i32.lt_s
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (i32.ge_s
 ;; CHECK-NEXT:    (local.get $y)
 ;; CHECK-NEXT:    (i32.const 4000000)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-different (param $x i32) (param $y i32) (result i32)
  ;; The locals are not equal. We do not optimize.
  (i32.or
   (i32.lt_s
    (local.get $x)
    (i32.const 0)
   )
   (i32.ge_s
    (local.get $y) ;; this changed
    (i32.const 4000000)
   )
  )
 )
)

