;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s --optimize-instructions -S -o - | filecheck %s

(module
 (func $test (param $x i32) (result i32)
  ;; Test conversions between signed and unsigned comparisons. Here we check if
  ;; x < 0 or x >= 4000000, but the comparisons are signed, so we are checking
  ;; if x >= 4000000 or the sign bit is set, which can be checked using a single
  ;; unsigned comparison.
  (i32.or
   (i32.lt_s
    (local.get $x)
    (i32.const 0)
   )
   (i32.ge_s
    (local.get $x)
    (i32.const 4000000)
   )
  )
 )

 (func $test-flipped (param $x i32) (result i32)
  (i32.or
   (i32.ge_s
    (local.get $x)
    (i32.const 4000000)
   )
   (i32.lt_s
    (local.get $x)
    (i32.const 0)
   )
  )
 )

 (func $test-tee (param $x i32) (result i32)
  (local $temp i32)
  (i32.or
   (i32.lt_s
    (local.tee $temp
     (local.get $x)
    )
    (i32.const 0)
   )
   (i32.ge_s
    (local.get $temp)
    (i32.const 4000000)
   )
  )
 )

 (func $test-tee-flipped (param $x i32) (result i32)
  (local $temp i32)
  (i32.or
   (i32.ge_s
    (local.tee $temp
     (local.get $x)
    )
    (i32.const 4000000)
   )
   (i32.lt_s
    (local.get $temp)
    (i32.const 0)
   )
  )
 )
)

