;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --remove-unused-module-elements -all                -S -o - | filecheck %s
;; RUN: foreach %s %t wasm-opt --remove-unused-module-elements -all --closed-world -S -o - | filecheck %s --check-prefix=CLOSD

;; Test that we see which tables are mutable, and optimize more when they are
;; immutable.

;; This table is immutable.
(module
  ;; CHECK:      (type $A (func))
  ;; CLOSD:      (type $A (func))
  (type $A (func))

  ;; CHECK:      (type $1 (func (result funcref)))

  ;; CHECK:      (table $table 22 funcref)
  ;; CLOSD:      (type $1 (func (result funcref)))

  ;; CLOSD:      (table $table 22 funcref)
  (table $table 22 funcref)

  ;; CHECK:      (elem declare func $func)

  ;; CHECK:      (export "run" (func $run))

  ;; CHECK:      (func $run (type $1) (result funcref)
  ;; CHECK-NEXT:  (call_indirect $table (type $A)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (ref.func $func)
  ;; CHECK-NEXT: )
  ;; CLOSD:      (elem declare func $func)

  ;; CLOSD:      (export "run" (func $run))

  ;; CLOSD:      (func $run (type $1) (result funcref)
  ;; CLOSD-NEXT:  (call_indirect $table (type $A)
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (ref.func $func)
  ;; CLOSD-NEXT: )
  (func $run (export "run") (result funcref)
    (call_indirect $table (type $A)
      (i32.const 0)
    )

    ;; Take a reference to the function, otherwise it can trivially be removed
    ;; as lacking any reference.
    (ref.func $func)
  )

  ;; CHECK:      (func $func (type $A)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (func $func (type $A)
  ;; CLOSD-NEXT:  (unreachable)
  ;; CLOSD-NEXT: )
  (func $func (type $A)
    ;; In open world we must assume the ref.func of this functions implies that
    ;; the outside can call us, but in closed world only calls inside the
    ;; module matter, and the table is immutable, so this will not be called (we
    ;; still keep it due to the reference, but can empty if out to unreachable).
    (drop (i32.const 42))
  )
)

;; As above, but $func is present in another table. It can still be optimized in
;; closed world.
(module
  ;; CHECK:      (type $A (func))
  ;; CLOSD:      (type $A (func))
  (type $A (func))

  ;; CHECK:      (type $1 (func (result funcref)))

  ;; CHECK:      (table $table 22 funcref)
  ;; CLOSD:      (type $1 (func (result funcref)))

  ;; CLOSD:      (table $table 22 funcref)
  (table $table 22 funcref)

  (table $other 22 funcref)

  (elem $elem (table $other) (i32.const 0) func $func)

  ;; CHECK:      (elem declare func $func)

  ;; CHECK:      (export "run" (func $run))

  ;; CHECK:      (func $run (type $1) (result funcref)
  ;; CHECK-NEXT:  (call_indirect $table (type $A)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (ref.func $func)
  ;; CHECK-NEXT: )
  ;; CLOSD:      (elem declare func $func)

  ;; CLOSD:      (export "run" (func $run))

  ;; CLOSD:      (func $run (type $1) (result funcref)
  ;; CLOSD-NEXT:  (call_indirect $table (type $A)
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (ref.func $func)
  ;; CLOSD-NEXT: )
  (func $run (export "run") (result funcref)
    (call_indirect $table (type $A)
      (i32.const 0)
    )
    (ref.func $func)
  )

  ;; CHECK:      (func $func (type $A)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (func $func (type $A)
  ;; CLOSD-NEXT:  (unreachable)
  ;; CLOSD-NEXT: )
  (func $func (type $A)
    (drop (i32.const 42))
  )
)

