;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --remove-unused-module-elements -all                -S -o - | filecheck %s
;; RUN: foreach %s %t wasm-opt --remove-unused-module-elements -all --closed-world -S -o - | filecheck %s --check-prefix=CLOSD

;; Test that we see which tables are mutable, and optimize more when they are
;; immutable.

;; This table is immutable.
(module
  ;; CHECK:      (type $A (func))
  ;; CLOSD:      (type $A (func))
  (type $A (func))

  ;; CHECK:      (type $1 (func (result funcref)))

  ;; CHECK:      (table $table 22 funcref)
  ;; CLOSD:      (type $1 (func (result funcref)))

  ;; CLOSD:      (table $table 22 funcref)
  (table $table 22 funcref)

  ;; CHECK:      (elem declare func $func)

  ;; CHECK:      (export "run" (func $run))

  ;; CHECK:      (func $run (type $1) (result funcref)
  ;; CHECK-NEXT:  (call_indirect $table (type $A)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (ref.func $func)
  ;; CHECK-NEXT: )
  ;; CLOSD:      (elem declare func $func)

  ;; CLOSD:      (export "run" (func $run))

  ;; CLOSD:      (func $run (type $1) (result funcref)
  ;; CLOSD-NEXT:  (call_indirect $table (type $A)
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (ref.func $func)
  ;; CLOSD-NEXT: )
  (func $run (export "run") (result funcref)
    (call_indirect $table (type $A)
      (i32.const 0)
    )

    ;; Take a reference to the function, otherwise it can trivially be removed
    ;; as lacking any reference.
    (ref.func $func)
  )

  ;; CHECK:      (func $func (type $A)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (func $func (type $A)
  ;; CLOSD-NEXT:  (unreachable)
  ;; CLOSD-NEXT: )
  (func $func (type $A)
    ;; In open world we must assume the ref.func of this functions implies that
    ;; the outside can call us, but in closed world only calls inside the
    ;; module matter, and the table is immutable, so this will not be called (we
    ;; still keep it due to the reference, but can empty if out to unreachable).
    (drop (i32.const 42))
  )
)

;; As above, but $func is present in another table. It can still be optimized in
;; closed world.
(module
  ;; CHECK:      (type $A (func))
  ;; CLOSD:      (type $A (func))
  (type $A (func))

  ;; CHECK:      (type $1 (func (result funcref)))

  ;; CHECK:      (table $table 22 funcref)
  ;; CLOSD:      (type $1 (func (result funcref)))

  ;; CLOSD:      (table $table 22 funcref)
  (table $table 22 funcref)

  (table $other 22 funcref)

  (elem $elem (table $other) (i32.const 0) func $func)

  ;; CHECK:      (elem declare func $func)

  ;; CHECK:      (export "run" (func $run))

  ;; CHECK:      (func $run (type $1) (result funcref)
  ;; CHECK-NEXT:  (call_indirect $table (type $A)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (ref.func $func)
  ;; CHECK-NEXT: )
  ;; CLOSD:      (elem declare func $func)

  ;; CLOSD:      (export "run" (func $run))

  ;; CLOSD:      (func $run (type $1) (result funcref)
  ;; CLOSD-NEXT:  (call_indirect $table (type $A)
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (ref.func $func)
  ;; CLOSD-NEXT: )
  (func $run (export "run") (result funcref)
    (call_indirect $table (type $A)
      (i32.const 0)
    )
    (ref.func $func)
  )

  ;; CHECK:      (func $func (type $A)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (func $func (type $A)
  ;; CLOSD-NEXT:  (unreachable)
  ;; CLOSD-NEXT: )
  (func $func (type $A)
    (drop (i32.const 42))
  )
)

;; As above, but move the elem to $table. Now $func is callable, and
;; unoptimizable.
(module
  ;; CHECK:      (type $A (func))
  ;; CLOSD:      (type $A (func))
  (type $A (func))

  ;; CHECK:      (type $1 (func (result funcref)))

  ;; CHECK:      (table $table 22 funcref)
  ;; CLOSD:      (type $1 (func (result funcref)))

  ;; CLOSD:      (table $table 22 funcref)
  (table $table 22 funcref)

  (table $other 22 funcref)

  ;; CHECK:      (elem $elem (i32.const 0) $func)
  ;; CLOSD:      (elem $elem (i32.const 0) $func)
  (elem $elem (table $table) (i32.const 0) func $func)

  ;; CHECK:      (export "run" (func $run))

  ;; CHECK:      (func $run (type $1) (result funcref)
  ;; CHECK-NEXT:  (call_indirect $table (type $A)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (ref.func $func)
  ;; CHECK-NEXT: )
  ;; CLOSD:      (export "run" (func $run))

  ;; CLOSD:      (func $run (type $1) (result funcref)
  ;; CLOSD-NEXT:  (call_indirect $table (type $A)
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (ref.func $func)
  ;; CLOSD-NEXT: )
  (func $run (export "run") (result funcref)
    (call_indirect $table (type $A)
      (i32.const 0)
    )
    (ref.func $func)
  )

  ;; CHECK:      (func $func (type $A)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (func $func (type $A)
  ;; CLOSD-NEXT:  (drop
  ;; CLOSD-NEXT:   (i32.const 42)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT: )
  (func $func (type $A)
    (drop (i32.const 42))
  )
)

;; This table is mutable because of a table.set, so we do not optimize.
(module
  ;; CHECK:      (type $A (func))
  ;; CLOSD:      (type $A (func))
  (type $A (func))

  ;; CHECK:      (table $table 22 funcref)
  ;; CLOSD:      (table $table 22 funcref)
  (table $table 22 funcref)

  ;; CHECK:      (elem declare func $func)

  ;; CHECK:      (export "run" (func $run))

  ;; CHECK:      (func $run (type $A)
  ;; CHECK-NEXT:  (table.set $table
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (ref.func $func)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call_indirect $table (type $A)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (elem declare func $func)

  ;; CLOSD:      (export "run" (func $run))

  ;; CLOSD:      (func $run (type $A)
  ;; CLOSD-NEXT:  (table.set $table
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:   (ref.func $func)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (call_indirect $table (type $A)
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT: )
  (func $run (export "run")
    (table.set $table
      (i32.const 0)
      (ref.func $func)
    )
    (call_indirect $table (type $A)
      (i32.const 0)
    )
  )

  ;; CHECK:      (func $func (type $A)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (func $func (type $A)
  ;; CLOSD-NEXT:  (drop
  ;; CLOSD-NEXT:   (i32.const 42)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT: )
  (func $func (type $A)
    (drop (i32.const 42))
  )
)

;; A table.fill prevents optimization.
(module
  ;; CHECK:      (type $A (func))
  ;; CLOSD:      (type $A (func))
  (type $A (func))

  ;; CHECK:      (table $table 22 funcref)
  ;; CLOSD:      (table $table 22 funcref)
  (table $table 22 funcref)

  ;; CHECK:      (elem declare func $func)

  ;; CHECK:      (export "run" (func $run))

  ;; CHECK:      (func $run (type $A)
  ;; CHECK-NEXT:  (table.fill $table
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (ref.func $func)
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call_indirect $table (type $A)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (elem declare func $func)

  ;; CLOSD:      (export "run" (func $run))

  ;; CLOSD:      (func $run (type $A)
  ;; CLOSD-NEXT:  (table.fill $table
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:   (ref.func $func)
  ;; CLOSD-NEXT:   (i32.const 1)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (call_indirect $table (type $A)
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT: )
  (func $run (export "run")
    (table.fill $table
      (i32.const 0)
      (ref.func $func)
      (i32.const 1)
    )
    (call_indirect $table (type $A)
      (i32.const 0)
    )
  )

  ;; CHECK:      (func $func (type $A)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (func $func (type $A)
  ;; CLOSD-NEXT:  (drop
  ;; CLOSD-NEXT:   (i32.const 42)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT: )
  (func $func (type $A)
    (drop (i32.const 42))
  )
)

;; A table.copy prevents optimization, but only in the written table, and
;; depending on the type: we write to $table but not to $other.
(module
  (rec
   ;; CHECK:      (rec
   ;; CHECK-NEXT:  (type $A (func))
   ;; CLOSD:      (rec
   ;; CLOSD-NEXT:  (type $A (func))
   (type $A (func))
   ;; CHECK:       (type $B (func))
   ;; CLOSD:       (type $B (func))
   (type $B (func))
  )

  ;; CHECK:      (type $2 (func))

  ;; CHECK:      (table $table 22 funcref)
  ;; CLOSD:      (type $2 (func))

  ;; CLOSD:      (table $table 22 funcref)
  (table $table 22 funcref)

  ;; CHECK:      (table $other 22 funcref)
  ;; CLOSD:      (table $other 22 funcref)
  (table $other 22 funcref)

  ;; CHECK:      (elem declare func $bar $func)

  ;; CHECK:      (export "run" (func $run))

  ;; CHECK:      (func $run (type $2)
  ;; CHECK-NEXT:  (table.copy $table $other
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:   (i32.const 2)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call_indirect $table (type $A)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call_indirect $other (type $B)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.func $func)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.func $bar)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (elem declare func $bar $func)

  ;; CLOSD:      (export "run" (func $run))

  ;; CLOSD:      (func $run (type $2)
  ;; CLOSD-NEXT:  (table.copy $table $other
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:   (i32.const 1)
  ;; CLOSD-NEXT:   (i32.const 2)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (call_indirect $table (type $A)
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (call_indirect $other (type $B)
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (drop
  ;; CLOSD-NEXT:   (ref.func $func)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (drop
  ;; CLOSD-NEXT:   (ref.func $bar)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT: )
  (func $run (export "run")
    (table.copy $table $other
      (i32.const 0)
      (i32.const 1)
      (i32.const 2)
    )
    (call_indirect $table (type $A)
      (i32.const 0)
    )
    (call_indirect $other (type $B)
      (i32.const 0)
    )
    ;; Refer to both, to avoid trivial optimization.
    (drop (ref.func $func))
    (drop (ref.func $bar))
  )

  ;; CHECK:      (func $func (type $A)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (func $func (type $A)
  ;; CLOSD-NEXT:  (drop
  ;; CLOSD-NEXT:   (i32.const 42)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT: )
  (func $func (type $A)
    ;; This cannot be optimized to unreachable because the table is mutable, a
    ;; reference was taken of it, and a call of the right type exists to that
    ;; table.
    (drop (i32.const 42))
  )

  ;; CHECK:      (func $bar (type $B)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1337)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (func $bar (type $B)
  ;; CLOSD-NEXT:  (unreachable)
  ;; CLOSD-NEXT: )
  (func $bar (type $B)
    ;; This can be optimized to unreachable because, while all other conditions
    ;; exist, the table is immutable.
    (drop (i32.const 1337))
  )
)

;; Flip the call_indirect types.
(module
  (rec
   ;; CHECK:      (rec
   ;; CHECK-NEXT:  (type $A (func))
   ;; CLOSD:      (rec
   ;; CLOSD-NEXT:  (type $A (func))
   (type $A (func))
   ;; CHECK:       (type $B (func))
   ;; CLOSD:       (type $B (func))
   (type $B (func))
  )

  ;; CHECK:      (type $2 (func))

  ;; CHECK:      (table $table 22 funcref)
  ;; CLOSD:      (type $2 (func))

  ;; CLOSD:      (table $table 22 funcref)
  (table $table 22 funcref)

  ;; CHECK:      (table $other 22 funcref)
  ;; CLOSD:      (table $other 22 funcref)
  (table $other 22 funcref)

  ;; CHECK:      (elem declare func $bar $func)

  ;; CHECK:      (export "run" (func $run))

  ;; CHECK:      (func $run (type $2)
  ;; CHECK-NEXT:  (table.copy $table $other
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:   (i32.const 2)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call_indirect $table (type $B)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call_indirect $other (type $A)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.func $func)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.func $bar)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (elem declare func $bar $func)

  ;; CLOSD:      (export "run" (func $run))

  ;; CLOSD:      (func $run (type $2)
  ;; CLOSD-NEXT:  (table.copy $table $other
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:   (i32.const 1)
  ;; CLOSD-NEXT:   (i32.const 2)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (call_indirect $table (type $B)
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (call_indirect $other (type $A)
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (drop
  ;; CLOSD-NEXT:   (ref.func $func)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (drop
  ;; CLOSD-NEXT:   (ref.func $bar)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT: )
  (func $run (export "run")
    (table.copy $table $other
      (i32.const 0)
      (i32.const 1)
      (i32.const 2)
    )
    (call_indirect $table (type $B) ;; this flipped
      (i32.const 0)
    )
    (call_indirect $other (type $A) ;; this flipped
      (i32.const 0)
    )
    ;; Refer to both, to avoid trivial optimization.
    (drop (ref.func $func))
    (drop (ref.func $bar))
  )

  ;; CHECK:      (func $func (type $A)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (func $func (type $A)
  ;; CLOSD-NEXT:  (unreachable)
  ;; CLOSD-NEXT: )
  (func $func (type $A)
    ;; No call_indirect of $A exists, so despite the mutable table, we can
    ;; optimize here.
    (drop (i32.const 42))
  )

  ;; CHECK:      (func $bar (type $B)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1337)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (func $bar (type $B)
  ;; CLOSD-NEXT:  (drop
  ;; CLOSD-NEXT:   (i32.const 1337)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT: )
  (func $bar (type $B)
    ;; This can be optimized: the table is immutable, and anyhow no
    ;; call_indirect of $B exists.
    (drop (i32.const 1337))
  )
)

;; A table.init prevents optimization.
(module
  ;; CHECK:      (type $A (func))
  ;; CLOSD:      (type $A (func))
  (type $A (func))

  ;; CHECK:      (table $table 22 funcref)
  ;; CLOSD:      (table $table 22 funcref)
  (table $table 22 funcref)

  ;; CHECK:      (elem $elem func)
  ;; CLOSD:      (elem $elem func)
  (elem $elem funcref)

  ;; CHECK:      (elem declare func $func)

  ;; CHECK:      (export "run" (func $run))

  ;; CHECK:      (func $run (type $A)
  ;; CHECK-NEXT:  (table.init $table $elem
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:   (i32.const 2)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call_indirect $table (type $A)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.func $func)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (elem declare func $func)

  ;; CLOSD:      (export "run" (func $run))

  ;; CLOSD:      (func $run (type $A)
  ;; CLOSD-NEXT:  (table.init $table $elem
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:   (i32.const 1)
  ;; CLOSD-NEXT:   (i32.const 2)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (call_indirect $table (type $A)
  ;; CLOSD-NEXT:   (i32.const 0)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT:  (drop
  ;; CLOSD-NEXT:   (ref.func $func)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT: )
  (func $run (export "run")
    (table.init $table $elem
      (i32.const 0)
      (i32.const 1)
      (i32.const 2)
    )
    (call_indirect $table (type $A)
      (i32.const 0)
    )
    (drop
      (ref.func $func)
    )
  )

  ;; CHECK:      (func $func (type $A)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; CLOSD:      (func $func (type $A)
  ;; CLOSD-NEXT:  (drop
  ;; CLOSD-NEXT:   (i32.const 42)
  ;; CLOSD-NEXT:  )
  ;; CLOSD-NEXT: )
  (func $func (type $A)
    (drop (i32.const 42))
  )
)

