;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; Show that type-generalizing can remove a cast that the normal optimization
;; pipeline cannot. We optimize the module with -O3 in both cases, but once with
;; generalization before.

;; RUN: foreach %s %t wasm-opt                     -O3 -all -tnh -S -o - | filecheck %s
;; RUN: foreach %s %t wasm-opt --type-generalizing -O3 -all -tnh -S -o - | filecheck %s --check-prefix=TYGEN

(module
  ;; CHECK:      (type $A (struct))
  ;; TYGEN:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func (param anyref)))

  ;; CHECK:      (type $2 (func (result i32)))

  ;; CHECK:      (global $g (mut (ref null $A)) (struct.new_default $A))
  ;; TYGEN:      (type $1 (func (param anyref)))

  ;; TYGEN:      (type $2 (func (result i32)))

  ;; TYGEN:      (global $g (mut (ref null $A)) (struct.new_default $A))
  (global $g (mut (ref null $A)) (struct.new $A))

  ;; CHECK:      (export "set" (func $set))

  ;; CHECK:      (export "get" (func $get))

  ;; CHECK:      (func $set (type $1) (param $0 anyref)
  ;; CHECK-NEXT:  (global.set $g
  ;; CHECK-NEXT:   (ref.cast (ref null $A)
  ;; CHECK-NEXT:    (local.get $0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; TYGEN:      (export "set" (func $set))

  ;; TYGEN:      (export "get" (func $get))

  ;; TYGEN:      (func $set (type $1) (param $0 anyref)
  ;; TYGEN-NEXT:  (global.set $g
  ;; TYGEN-NEXT:   (ref.cast (ref null $A)
  ;; TYGEN-NEXT:    (local.get $0)
  ;; TYGEN-NEXT:   )
  ;; TYGEN-NEXT:  )
  ;; TYGEN-NEXT: )
  (func $set (export "set") (param $any anyref)
    ;; Cast to $A & stash that in the global, but then only use it below to
    ;; check for nullability. The global does't need to be anything more than
    ;; anyref and we don't need the cast (in TYGEN).
    (global.set $g
      (ref.cast (ref null $A)
        (local.get $any)
      )
    )
  )

  ;; CHECK:      (func $get (type $2) (result i32)
  ;; CHECK-NEXT:  (ref.is_null
  ;; CHECK-NEXT:   (global.get $g)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; TYGEN:      (func $get (type $2) (result i32)
  ;; TYGEN-NEXT:  (ref.is_null
  ;; TYGEN-NEXT:   (global.get $g)
  ;; TYGEN-NEXT:  )
  ;; TYGEN-NEXT: )
  (func $get (export "get") (result i32)
    (ref.is_null
      (global.get $g)
    )
  )
)

