;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --type-generalizing -all -S -o - | filecheck %s

;; With no constraints on it, this global can be anyref.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (global $g (mut anyref) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))
)

;; A global.get constrains us as it feeds into a ref.eq, so we must be eq.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $g (mut eqref) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.eq
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (ref.eq
        (global.get $g)
        (global.get $g)
      )
    )
  )
)

;; Exported globals are roots: we do not change their types.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $g (mut (ref $A)) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (export "g" (global $g))
  (export "g" (global $g))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.eq
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (ref.eq
        (global.get $g)
        (global.get $g)
      )
    )
  )
)

;; One global influences another. Here $g has two constraints: the exported
;; global $exp-nn which requires non-null any, and the ref.eq which requires
;; nullable eq. Together, we end up with non-null eq.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $exp-nn (mut (ref any)) (struct.new_default $A))
  (global $exp-nn (mut (ref any)) (struct.new $A))

  ;; CHECK:      (global $g (mut (ref eq)) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (export "exp" (global $exp-nn))
  (export "exp" (global $exp-nn))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (global.set $exp-nn
  ;; CHECK-NEXT:   (global.get $g)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.eq
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    ;; Use $g in a set to the exported global, and in a ref.eq.
    (global.set $exp-nn
      (global.get $g)
    )
    (drop
      (ref.eq
        (global.get $g)
        (global.get $g)
      )
    )
  )
)

;; Chains of globals.
(module
  ;; CHECK:      (type $A (sub (struct)))
  (type $A (sub (struct)))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $exp-nn (mut (ref any)) (struct.new_default $A))
  (global $exp-nn (mut (ref any)) (struct.new $A))

  ;; CHECK:      (global $exp-A (mut (ref null $A)) (struct.new_default $A))
  (global $exp-A (mut (ref null $A)) (struct.new $A))

  ;; CHECK:      (global $g (mut (ref any)) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (global $h (mut (ref null $A)) (struct.new_default $A))
  (global $h (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (global $i (mut (ref $A)) (struct.new_default $A))
  (global $i (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (export "exp-nn" (global $exp-nn))
  (export "exp-nn" (global $exp-nn))

  ;; CHECK:      (export "exp-A" (global $exp-A))
  (export "exp-A" (global $exp-A))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (global.set $exp-nn
  ;; CHECK-NEXT:   (global.get $g)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $exp-A
  ;; CHECK-NEXT:   (global.get $h)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $g
  ;; CHECK-NEXT:   (global.get $i)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $h
  ;; CHECK-NEXT:   (global.get $i)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    ;; Force $g to be non-nullable.
    (global.set $exp-nn
      (global.get $g)
    )
    ;; Force $h to be $A
    (global.set $exp-A
      (global.get $h)
    )
    ;; Force $i to be both non-nullable and $A.
    (global.set $g
      (global.get $i)
    )
    (global.set $h
      (global.get $i)
    )
  )
)

;; As above, but add a loop between globals.
(module
  ;; CHECK:      (type $A (sub (struct)))
  (type $A (sub (struct)))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $exp-nn (mut (ref any)) (struct.new_default $A))
  (global $exp-nn (mut (ref any)) (struct.new $A))

  ;; CHECK:      (global $exp-A (mut (ref null $A)) (struct.new_default $A))
  (global $exp-A (mut (ref null $A)) (struct.new $A))

  ;; CHECK:      (global $g (mut (ref any)) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (global $h (mut (ref $A)) (struct.new_default $A))
  (global $h (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (global $i (mut (ref $A)) (struct.new_default $A))
  (global $i (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (export "exp-nn" (global $exp-nn))
  (export "exp-nn" (global $exp-nn))

  ;; CHECK:      (export "exp-A" (global $exp-A))
  (export "exp-A" (global $exp-A))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (global.set $exp-nn
  ;; CHECK-NEXT:   (global.get $g)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $exp-A
  ;; CHECK-NEXT:   (global.get $h)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $g
  ;; CHECK-NEXT:   (global.get $i)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $h
  ;; CHECK-NEXT:   (global.get $i)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $i
  ;; CHECK-NEXT:   (global.get $h)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (global.set $exp-nn
      (global.get $g)
    )
    (global.set $exp-A
      (global.get $h)
    )
    (global.set $g
      (global.get $i)
    )
    (global.set $h
      (global.get $i)
    )
    ;; Add an edge between $h and $i the other way. Now $h must be refined
    ;; enough to write to $i, making $h (ref $A) like $i.
    (global.set $i
      (global.get $h)
    )
  )
)

;; Imported globals are roots.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (import "a" "b" (global $g (mut (ref $A))))
  (import "a" "b" (global $g (mut (ref $A))))
)

;; Imported globals can be ignored and we should not error.
(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (import "a" "b" (func $f (type $0)))
  (import "a" "b" (func $f))
)

;; The function result constrains the global. We can only make it nullable.
(module
  ;; CHECK:      (type $F (func))
  (type $F (func))

  ;; CHECK:      (type $1 (func (result (ref null $F))))

  ;; CHECK:      (global $global (ref null $F) (ref.func $F))
  (global $global (ref $F) (ref.func $F))

  ;; CHECK:      (func $F (type $F)
  ;; CHECK-NEXT: )
  (func $F (type $F)
  )

  ;; CHECK:      (func $test (type $1) (result (ref null $F))
  ;; CHECK-NEXT:  (global.get $global)
  ;; CHECK-NEXT: )
  (func $test (result (ref null $F))
    (global.get $global)
  )
)

;; A drop does not constrain the global.
(module
  ;; CHECK:      (type $F (func))
  (type $F (func))

  ;; CHECK:      (global $global funcref (ref.func $F))
  (global $global (ref $F) (ref.func $F))

  ;; CHECK:      (func $F (type $F)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (global.get $global)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $F (type $F)
    (drop
      (global.get $global)
    )
  )
)

;; The block's type does not constrain the global, since it is dropped.
(module
  ;; CHECK:      (type $F (func))
  (type $F (func))

  ;; CHECK:      (global $global funcref (ref.func $F))
  (global $global (ref $F) (ref.func $F))

  ;; CHECK:      (func $F (type $F)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block (result funcref)
  ;; CHECK-NEXT:    (global.get $global)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $F (type $F)
   (drop
      (block (result (ref null $F))
        (global.get $global)
      )
    )
  )
)

;; The function result constrains the block and the global.
(module
  ;; CHECK:      (type $F (func))
  (type $F (func))

  ;; CHECK:      (type $1 (func (result (ref func))))

  ;; CHECK:      (global $global (ref func) (ref.func $F))
  (global $global (ref $F) (ref.func $F))

  ;; CHECK:      (func $F (type $F)
  ;; CHECK-NEXT: )
  (func $F (type $F)
  )

  ;; CHECK:      (func $test (type $1) (result (ref func))
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (block (result (ref func))
  ;; CHECK-NEXT:   (global.get $global)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test (result (ref func))
    (nop) ;; avoid a trivial block
    (block (result (ref $F))
      (global.get $global)
    )
  )
)

;; The drop does not constrain the if, so we can generalize it to anyref.
(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (func $test (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (if (result anyref)
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:    (then
  ;; CHECK-NEXT:     (ref.i31
  ;; CHECK-NEXT:      (i32.const 0)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (else
  ;; CHECK-NEXT:     (nop)
  ;; CHECK-NEXT:     (ref.null none)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (if (result i31ref)
        (i32.const 0)
        (then
          (ref.i31
            (i32.const 0)
          )
        )
        (else
          (nop) ;; Avoid a trivial block here, so we test the typing of this
                ;; block as well.
          (ref.null none)
        )
      )
    )
  )
)

;; Generalize a loop's type.
(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (elem declare func $test)

  ;; CHECK:      (func $test (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (loop (result funcref)
  ;; CHECK-NEXT:    (ref.func $test)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (loop (result (ref func))
        (ref.func $test)
      )
    )
  )
)

;; Generalize a select's type.
(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (elem declare func $test)

  ;; CHECK:      (func $test (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (select (result funcref)
  ;; CHECK-NEXT:    (ref.func $test)
  ;; CHECK-NEXT:    (ref.func $test)
  ;; CHECK-NEXT:    (i32.const 1)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (select (result (ref func))
        (ref.func $test)
        (ref.func $test)
        (i32.const 1)
      )
    )
  )
)

;; Generalize a try's type.
(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (elem declare func $test)

  ;; CHECK:      (func $test (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (try (result funcref)
  ;; CHECK-NEXT:    (do
  ;; CHECK-NEXT:     (ref.func $test)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (try (result (ref func))
        (do
          (ref.func $test)
        )
      )
    )
  )
)

;; Generalize a try_table's type.
(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (elem declare func $test)

  ;; CHECK:      (func $test (type $0)
  ;; CHECK-NEXT:  (block $block
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (try_table (result funcref) (catch_all $block)
  ;; CHECK-NEXT:     (ref.func $test)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (block $block
      (drop
        (try_table (result (ref func)) (catch_all $block)
          (ref.func $test)
        )
      )
    )
  )
)

