;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --type-generalizing -all -S -o - | filecheck %s

;; With no constraints on it, this global can be anyref, but it is unused, so
;; we ignore it. (Having no constraints on it, we don't bother doing anything.)
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (global $g (mut anyref) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))
)

;; A global.get constrains us as it feeds into a ref.eq, so $g must be eq.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $g (mut eqref) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.eq
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (ref.eq
        (global.get $g)
        (global.get $g)
      )
    )
  )
)

;; Exported globals are roots: we do not change their types.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $g (mut (ref $A)) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (export "g" (global $g))
  (export "g" (global $g))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.eq
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (ref.eq
        (global.get $g)
        (global.get $g)
      )
    )
  )
)

;; One global influences another. Here $g has two constraints: the exported
;; global $exp-nn which requires non-null any, and the ref.eq which requires
;; nullable eq. Together, we end up with non-null eq.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $exp-nn (mut (ref any)) (struct.new_default $A))
  (global $exp-nn (mut (ref any)) (struct.new $A))

  ;; CHECK:      (global $g (mut (ref eq)) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (export "exp" (global $exp-nn))
  (export "exp" (global $exp-nn))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (global.set $exp-nn
  ;; CHECK-NEXT:   (global.get $g)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.eq
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    ;; Use $g in a set to the exported global, and in a ref.eq.
    (global.set $exp-nn
      (global.get $g)
    )
    (drop
      (ref.eq
        (global.get $g)
        (global.get $g)
      )
    )
  )
)

;; Chains of globals.
(module
  ;; CHECK:      (type $A (sub (struct)))
  (type $A (sub (struct)))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $exp-nn (mut (ref any)) (struct.new_default $A))
  (global $exp-nn (mut (ref any)) (struct.new $A))

  ;; CHECK:      (global $exp-A (mut (ref null $A)) (struct.new_default $A))
  (global $exp-A (mut (ref null $A)) (struct.new $A))

  ;; CHECK:      (global $g (mut (ref any)) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (global $h (mut (ref null $A)) (struct.new_default $A))
  (global $h (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (global $i (mut (ref $A)) (struct.new_default $A))
  (global $i (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (export "exp-nn" (global $exp-nn))
  (export "exp-nn" (global $exp-nn))

  ;; CHECK:      (export "exp-A" (global $exp-A))
  (export "exp-A" (global $exp-A))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (global.set $exp-nn
  ;; CHECK-NEXT:   (global.get $g)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $exp-A
  ;; CHECK-NEXT:   (global.get $h)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $g
  ;; CHECK-NEXT:   (global.get $i)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $h
  ;; CHECK-NEXT:   (global.get $i)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    ;; Force $g to be non-nullable.
    (global.set $exp-nn
      (global.get $g)
    )
    ;; Force $h to be $A
    (global.set $exp-A
      (global.get $h)
    )
    ;; Force $i to be both non-nullable and $A.
    (global.set $g
      (global.get $i)
    )
    (global.set $h
      (global.get $i)
    )
  )
)

;; As above, but add a loop between globals.
(module
  ;; CHECK:      (type $A (sub (struct)))
  (type $A (sub (struct)))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $exp-nn (mut (ref any)) (struct.new_default $A))
  (global $exp-nn (mut (ref any)) (struct.new $A))

  ;; CHECK:      (global $exp-A (mut (ref null $A)) (struct.new_default $A))
  (global $exp-A (mut (ref null $A)) (struct.new $A))

  ;; CHECK:      (global $g (mut (ref any)) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (global $h (mut (ref $A)) (struct.new_default $A))
  (global $h (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (global $i (mut (ref $A)) (struct.new_default $A))
  (global $i (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (export "exp-nn" (global $exp-nn))
  (export "exp-nn" (global $exp-nn))

  ;; CHECK:      (export "exp-A" (global $exp-A))
  (export "exp-A" (global $exp-A))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (global.set $exp-nn
  ;; CHECK-NEXT:   (global.get $g)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $exp-A
  ;; CHECK-NEXT:   (global.get $h)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $g
  ;; CHECK-NEXT:   (global.get $i)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $h
  ;; CHECK-NEXT:   (global.get $i)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $i
  ;; CHECK-NEXT:   (global.get $h)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (global.set $exp-nn
      (global.get $g)
    )
    (global.set $exp-A
      (global.get $h)
    )
    (global.set $g
      (global.get $i)
    )
    (global.set $h
      (global.get $i)
    )
    ;; Add an edge between $h and $i the other way. Now $h must be refined
    ;; enough to write to $i, making $h (ref $A) like $i.
    (global.set $i
      (global.get $h)
    )
  )
)

;; Imported globals are roots.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (import "a" "b" (global $g (mut (ref $A))))
  (import "a" "b" (global $g (mut (ref $A))))
)

;; Imported globals can be ignored and we should not error.
(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (import "a" "b" (func $f (type $0)))
  (import "a" "b" (func $f))
)

;; The function result constrains the global. We can only make it nullable.
(module
  ;; CHECK:      (type $F (func))
  (type $F (func))

  ;; CHECK:      (type $1 (func (result (ref null $F))))

  ;; CHECK:      (global $global (ref null $F) (ref.func $F))
  (global $global (ref $F) (ref.func $F))

  ;; CHECK:      (func $F (type $F)
  ;; CHECK-NEXT: )
  (func $F (type $F)
  )

  ;; CHECK:      (func $test (type $1) (result (ref null $F))
  ;; CHECK-NEXT:  (global.get $global)
  ;; CHECK-NEXT: )
  (func $test (result (ref null $F))
    (global.get $global)
  )
)

;; A drop does not constrain the global.
(module
  ;; CHECK:      (type $F (func))
  (type $F (func))

  ;; CHECK:      (global $global funcref (ref.func $F))
  (global $global (ref $F) (ref.func $F))

  ;; CHECK:      (func $F (type $F)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (global.get $global)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $F (type $F)
    (drop
      (global.get $global)
    )
  )
)

;; A ref.is_null does not constrain the global.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $g (mut anyref) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.is_null
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (ref.is_null
        (global.get $g)
      )
    )
  )
)

;; The block's type does not constrain the global, since it is dropped.
(module
  ;; CHECK:      (type $F (func))
  (type $F (func))

  ;; CHECK:      (global $global funcref (ref.func $F))
  (global $global (ref $F) (ref.func $F))

  ;; CHECK:      (func $F (type $F)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block (result funcref)
  ;; CHECK-NEXT:    (global.get $global)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $F (type $F)
    (drop
      (block (result (ref null $F))
        (global.get $global)
      )
    )
  )
)

;; The function result constrains the block and the global.
(module
  ;; CHECK:      (type $F (func))
  (type $F (func))

  ;; CHECK:      (type $1 (func (result (ref func))))

  ;; CHECK:      (global $global (ref func) (ref.func $F))
  (global $global (ref $F) (ref.func $F))

  ;; CHECK:      (func $F (type $F)
  ;; CHECK-NEXT: )
  (func $F (type $F)
  )

  ;; CHECK:      (func $test (type $1) (result (ref func))
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (block (result (ref func))
  ;; CHECK-NEXT:   (global.get $global)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test (result (ref func))
    (nop) ;; avoid a trivial block
    (block (result (ref $F))
      (global.get $global)
    )
  )
)

;; The drop does not constrain the if, so we can generalize it to anyref (and
;; the global as well).
(module

  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (global $g anyref (ref.i31
  ;; CHECK-NEXT:  (i32.const 42)
  ;; CHECK-NEXT: ))
  (global $g (ref i31) (ref.i31 (i32.const 42)))

  ;; CHECK:      (func $test (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (if (result anyref)
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:    (then
  ;; CHECK-NEXT:     (global.get $g)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (else
  ;; CHECK-NEXT:     (nop)
  ;; CHECK-NEXT:     (ref.null none)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (if (result i31ref)
        (i32.const 0)
        (then
          (global.get $g)
        )
        (else
          (nop) ;; Avoid a trivial block here, so we test the typing of this
                ;; block does not cause errors.
          (ref.null none)
        )
      )
    )
  )
)

;; Generalize a loop's type.
(module

  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (global $g funcref (ref.func $test))
  (global $g (ref func) (ref.func $test))

  ;; CHECK:      (func $test (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (loop (result funcref)
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (loop (result (ref func))
        (global.get $g)
      )
    )
  )
)

;; Generalize a select's type.
(module

  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (global $g funcref (ref.func $test))
  (global $g (ref func) (ref.func $test))

  ;; CHECK:      (func $test (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (select (result funcref)
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:    (i32.const 1)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (select (result (ref func))
        (global.get $g)
        (global.get $g)
        (i32.const 1)
      )
    )
  )
)

;; Generalize a try's type.
(module

  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (global $g funcref (ref.func $test))
  (global $g (ref func) (ref.func $test))

  ;; CHECK:      (func $test (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (try (result funcref)
  ;; CHECK-NEXT:    (do
  ;; CHECK-NEXT:     (global.get $g)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (try (result (ref func))
        (do
          (global.get $g)
        )
      )
    )
  )
)

;; Generalize a try_table's type.
(module

  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (global $g funcref (ref.func $test))
  (global $g (ref func) (ref.func $test))

  ;; CHECK:      (func $test (type $0)
  ;; CHECK-NEXT:  (block $block
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (try_table (result funcref) (catch_all $block)
  ;; CHECK-NEXT:     (global.get $g)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (block $block
      (drop
        (try_table (result (ref func)) (catch_all $block)
          (global.get $g)
        )
      )
    )
  )
)

;; br_on_cast_fail: here we can relax the nullability of the input type, but
;; not go to anyref (as then we'd be sending anyref to the block, which
;; requires more).
(module
  ;; CHECK:      (type $array (array i16))
  (type $array (array i16))

  ;; CHECK:      (type $1 (func (result (ref null $array))))

  ;; CHECK:      (global $g (ref $array) (array.new_default $array
  ;; CHECK-NEXT:  (i32.const 0)
  ;; CHECK-NEXT: ))
  (global $g (ref $array) (array.new_default $array (i32.const 0)))

  ;; CHECK:      (func $test (type $1) (result (ref null $array))
  ;; CHECK-NEXT:  (block $block (result (ref null $array))
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (br_on_cast_fail $block (ref $array) (ref $array)
  ;; CHECK-NEXT:     (block (result (ref $array))
  ;; CHECK-NEXT:      (global.get $g)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (ref.null none)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test (result (ref null $array))
    (block $block (result (ref null $array))
      (drop
        (br_on_cast_fail $block (ref $array) (ref $array)
          (block (result (ref $array)) ;; this can be nullable
            (global.get $g)
          )
        )
      )
      (ref.null $array)
    )
  )
)

;; As above, with br_on_non_null.
(module
  ;; CHECK:      (type $array (array i16))
  (type $array (array i16))

  ;; CHECK:      (type $1 (func (result (ref null $array))))

  ;; CHECK:      (global $g (ref $array) (array.new_default $array
  ;; CHECK-NEXT:  (i32.const 0)
  ;; CHECK-NEXT: ))
  (global $g (ref $array) (array.new_default $array (i32.const 0)))

  ;; CHECK:      (func $test (type $1) (result (ref null $array))
  ;; CHECK-NEXT:  (block $block (result (ref null $array))
  ;; CHECK-NEXT:   (br_on_non_null $block
  ;; CHECK-NEXT:    (block (result (ref $array))
  ;; CHECK-NEXT:     (global.get $g)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (ref.null none)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test (result (ref null $array))
    (block $block (result (ref null $array))
      (br_on_non_null $block
        (block (result (ref $array)) ;; this can be nullable
          (global.get $g)
        )
      )
      (ref.null $array)
    )
  )
)

;; As above, with br_on_cast_desc_fail.
(module
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $A (descriptor $B (struct)))
    (type $A (descriptor $B (struct)))
    ;; CHECK:       (type $B (describes $A (struct)))
    (type $B (describes $A (struct)))
  )

  ;; CHECK:      (type $2 (func (result (ref null $A))))

  ;; CHECK:      (global $g (ref $A) (struct.new_default $A
  ;; CHECK-NEXT:  (struct.new_default $B)
  ;; CHECK-NEXT: ))
  (global $g (ref $A) (struct.new $A
    (struct.new $B)
  ))

  ;; CHECK:      (func $test (type $2) (result (ref null $A))
  ;; CHECK-NEXT:  (block $block (result (ref null $A))
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (br_on_cast_desc_fail $block (ref $A) (ref (exact $A))
  ;; CHECK-NEXT:     (block (result (ref $A))
  ;; CHECK-NEXT:      (global.get $g)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (struct.new_default $B)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (ref.null none)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test (result (ref null $A))
    (block $block (result (ref null $A))
      (drop
        (br_on_cast_desc_fail $block (ref $A) (ref $A)
          (block (result (ref $A)) ;; this can be nullable
            (global.get $g)
          )
          (struct.new $B)
        )
      )
      (ref.null $A)
    )
  )
)

;; Struct operations, like struct.set, require that their reference input be a
;; struct type. We avoid generalizing them and leave them as is, forcing the
;; block here to remain unchanged.
(module
  ;; CHECK:      (type $A (struct (field (mut i32))))
  (type $A (struct (field (mut i32))))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (struct.set $A 0
  ;; CHECK-NEXT:   (block (result (ref (exact $A)))
  ;; CHECK-NEXT:    (struct.new_default $A)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (struct.set $A 0
      (block (result (ref (exact $A)))
        (struct.new_default $A)
      )
      (i32.const 42)
    )
  )
)

;; The function result forces the global to be (ref eq). We also have a use of
;; $g in a struct.set, which forces it to be a proper struct type.
(module
  ;; CHECK:      (type $A (struct (field (mut i32))))
  (type $A (struct (field (mut i32))))

  ;; CHECK:      (type $1 (func (result (ref eq))))

  ;; CHECK:      (global $g (ref $A) (struct.new_default $A))
  (global $g (ref $A) (struct.new_default $A))

  ;; CHECK:      (func $test (type $1) (result (ref eq))
  ;; CHECK-NEXT:  (struct.set $A 0
  ;; CHECK-NEXT:   (global.get $g)
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.get $g)
  ;; CHECK-NEXT: )
  (func $test (result (ref eq))
    (struct.set $A 0
      (global.get $g)
      (i32.const 42)
    )
    (global.get $g)
  )
)

;; Array operations require array inputs. As with structs, we avoid generalizing
;; them. TODO: We could generalize to arrayref
(module
  ;; CHECK:      (type $array (array i16))
  (type $array (array i16))

  ;; CHECK:      (type $1 (func (result i32)))

  ;; CHECK:      (global $g (ref $array) (array.new_default $array
  ;; CHECK-NEXT:  (i32.const 0)
  ;; CHECK-NEXT: ))
  (global $g (ref $array) (array.new_default $array (i32.const 0)))

  ;; CHECK:      (func $test (type $1) (result i32)
  ;; CHECK-NEXT:  (array.len
  ;; CHECK-NEXT:   (global.get $g)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test (result i32)
    (array.len
      (global.get $g)
    )
  )
)

;; We must refinalize after generalizing here, to not break validation: the
;; select must be (ref nofunc), even though the outer constraint only requires
;; funcref.
(module
  ;; CHECK:      (type $0 (func (result funcref)))

  ;; CHECK:      (func $0 (type $0) (result funcref)
  ;; CHECK-NEXT:  (select (result (ref nofunc))
  ;; CHECK-NEXT:   (ref.as_non_null
  ;; CHECK-NEXT:    (ref.null nofunc)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (ref.as_non_null
  ;; CHECK-NEXT:    (ref.null nofunc)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $0 (result funcref)
    (select (result (ref nofunc))
      (ref.as_non_null
        (ref.null nofunc)
      )
      (ref.as_non_null
        (ref.null nofunc)
      )
      (i32.const 0)
    )
  )
)

;; A chain of globals that read each other in the global scope. We must keep
;; the global $g refined so that $h is refined enough for the function's result.
(module
  ;; CHECK:      (type $struct (struct))
  (type $struct (struct))

  ;; CHECK:      (type $1 (func (result (ref $struct))))

  ;; CHECK:      (global $g (ref $struct) (struct.new_default $struct))
  (global $g (ref $struct) (struct.new_default $struct))

  ;; CHECK:      (global $h (ref $struct) (global.get $g))
  (global $h (ref $struct) (global.get $g))

  ;; CHECK:      (func $test (type $1) (result (ref $struct))
  ;; CHECK-NEXT:  (global.get $h)
  ;; CHECK-NEXT: )
  (func $test (result (ref $struct))
    (global.get $h)
  )
)


;; $g is constrained by a ref.eq and also has another use in br_on_null which we
;; do not optimize atm, which forces the global to not be generalized.
(module
 ;; CHECK:      (type $array (array i8))
 (type $array (array i8))

 ;; CHECK:      (type $1 (func))

 ;; CHECK:      (global $g (ref $array) (array.new_fixed $array 0))
 (global $g (ref $array) (array.new_fixed $array 0))

 ;; CHECK:      (func $test (type $1)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (ref.eq
 ;; CHECK-NEXT:    (global.get $g)
 ;; CHECK-NEXT:    (global.get $g)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $block
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (br_on_null $block
 ;; CHECK-NEXT:     (global.get $g)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $test
  (drop
   (ref.eq
    (global.get $g)
    (global.get $g)
   )
  )
  (block $block
   (drop
    (br_on_null $block
     (global.get $g)
    )
   )
  )
 )
)

;; $g can be generalized to eqref. The global $h must be generalized at the
;; same time, to not break validation, and it can be anyref.
(module
  ;; CHECK:      (type $array (array i8))
  (type $array (array i8))

  ;; CHECK:      (type $1 (func (result i32)))

  ;; CHECK:      (global $g eqref (array.new_fixed $array 0))
  (global $g arrayref (array.new_fixed $array 0))

  ;; CHECK:      (global $h (mut anyref) (global.get $g))
  (global $h (mut arrayref) (global.get $g))

  ;; CHECK:      (func $test (type $1) (result i32)
  ;; CHECK-NEXT:  (ref.eq
  ;; CHECK-NEXT:   (global.get $g)
  ;; CHECK-NEXT:   (global.get $g)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test (result i32)
    (ref.eq
      (global.get $g)
      (global.get $g)
    )
  )
)

;; Generalization of a local type.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func (param (ref null $A))))

  ;; CHECK:      (func $test (type $1) (param $p (ref null $A))
  ;; CHECK-NEXT:  (local $l-reads (ref null $A))
  ;; CHECK-NEXT:  (local $l-tee anyref)
  ;; CHECK-NEXT:  (local $l-unused anyref)
  ;; CHECK-NEXT:  (local.set $p
  ;; CHECK-NEXT:   (local.get $l-reads)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (local.get $p)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (local.get $l-reads)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (local.get $l-tee)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (local.tee $l-tee
  ;; CHECK-NEXT:    (local.get $l-tee)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test (param $p (ref null $A))
    ;; The parameter cannot be changed, but the last two locals can.
    (local $l-reads (ref null $A))
    (local $l-tee (ref null $A))
    (local $l-unused (ref null $A))

    ;; Prevent the first local from being generalized.
    (local.set $p
      (local.get $l-reads)
    )

    (drop
      (local.get $p)
    )
    (drop
      (local.get $l-reads)
    )
    (drop
      (local.get $l-tee)
    )

    ;; Verify we update tees (or the IR would not validate).
    (drop
      (local.tee $l-tee
        (local.get $l-tee)
      )
    )
  )
)

;; br_if type updating. Here the global $g can be made anyref, as can the
;; local. The br_if then sends along that generalized type.
(module
  ;; CHECK:      (type $A (sub (struct)))
  (type $A (sub (struct)))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $g anyref (struct.new_default $A))
  (global $g (ref $A) (struct.new $A))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (local $temp anyref)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $block (result anyref)
  ;; CHECK-NEXT:    (local.tee $temp
  ;; CHECK-NEXT:     (br_if $block
  ;; CHECK-NEXT:      (global.get $g)
  ;; CHECK-NEXT:      (i32.const 0)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (local $temp (ref null $A))
    (drop
      (block $block (result (ref null $A))
        (local.tee $temp
          (br_if $block
            (global.get $g)
            (i32.const 0)
          )
        )
      )
    )
  )
)

;; The local can be eqref, but not anyref, because the tee must be eqref.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (local $temp eqref)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.eq
  ;; CHECK-NEXT:    (local.tee $temp
  ;; CHECK-NEXT:     (struct.new_default $A)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (struct.new_default $A)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (local $temp (ref $A))
    (drop
      (ref.eq
        (local.tee $temp
          (struct.new $A)
        )
        (struct.new $A)
      )
    )
  )
)

;; The br_on_non_null is not yet optimized, so its child tee is rooted and
;; ungeneralized. We cannot generalize either local.
(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (func $test (type $0)
  ;; CHECK-NEXT:  (local $0 (ref struct))
  ;; CHECK-NEXT:  (local $1 (ref struct))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $block (result (ref struct))
  ;; CHECK-NEXT:    (br_on_non_null $block
  ;; CHECK-NEXT:     (local.tee $1
  ;; CHECK-NEXT:      (br_if $block
  ;; CHECK-NEXT:       (local.tee $0
  ;; CHECK-NEXT:        (struct.new_default $A)
  ;; CHECK-NEXT:       )
  ;; CHECK-NEXT:       (i32.const 0)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (return)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (local $0 (ref struct))
    (local $1 (ref struct))
    (drop
      (block $block (result (ref struct))
        (br_on_non_null $block
          (local.tee $1
            (br_if $block
              (local.tee $0
                (struct.new_default $A)
              )
              (i32.const 0)
            )
          )
        )
        (return)
      )
    )
  )
)

;; ref.as_non_null has a different type going out than going it: it has a
;; fallthrough, but it changes the type. We should not enforce the same type on
;; both sides, and keep the local as eqref.
(module
  ;; CHECK:      (type $0 (func (result (ref eq))))

  ;; CHECK:      (func $test (type $0) (result (ref eq))
  ;; CHECK-NEXT:  (local $temp eqref)
  ;; CHECK-NEXT:  (ref.as_non_null
  ;; CHECK-NEXT:   (local.get $temp)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test (result (ref eq))
    (local $temp eqref)
    (ref.as_non_null
      (local.get $temp)
    )
  )
)

;; Do not error on unreachable code.
(module
  ;; CHECK:      (type $0 (func (result structref)))

  ;; CHECK:      (func $test (type $0) (result structref)
  ;; CHECK-NEXT:  (ref.is_null
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test (result structref)
    (ref.is_null
      (unreachable)
    )
  )
)

;; TODO: cleanup. this is for Fallthrougheffectbehavior::ignore
(module
 ;; CHECK:      (type $1 (struct))
 (type $1 (struct))
 ;; CHECK:      (type $3 (array (mut i16)))
 (type $3 (array (mut i16)))
 ;; CHECK:      (type $0 (func))
 (type $0 (func))
 ;; CHECK:      (func $109 (type $0)
 ;; CHECK-NEXT:  (local $1 (ref (exact $1)))
 ;; CHECK-NEXT:  (local $0 (ref string))
 ;; CHECK-NEXT:  (local $3 (ref $3))
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (block $block (result (ref (exact $1)))
 ;; CHECK-NEXT:    (ref.cast (ref (exact $1))
 ;; CHECK-NEXT:     (br_if $block
 ;; CHECK-NEXT:      (block (result (ref (exact $1)))
 ;; CHECK-NEXT:       (local.set $1
 ;; CHECK-NEXT:        (struct.new_default $1)
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:       (local.set $0
 ;; CHECK-NEXT:        (string.const "\f0\90\8d\88953\c2\a3")
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:       (local.get $1)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:      (if (result i32)
 ;; CHECK-NEXT:       (array.len
 ;; CHECK-NEXT:        (local.tee $3
 ;; CHECK-NEXT:         (array.new_default $3
 ;; CHECK-NEXT:          (i32.const 0)
 ;; CHECK-NEXT:         )
 ;; CHECK-NEXT:        )
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:       (then
 ;; CHECK-NEXT:        (string.encode_wtf16_array
 ;; CHECK-NEXT:         (local.get $0)
 ;; CHECK-NEXT:         (local.get $3)
 ;; CHECK-NEXT:         (i32.const 0)
 ;; CHECK-NEXT:        )
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:       (else
 ;; CHECK-NEXT:        (i32.const 0)
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $109 (type $0)
  (local $1 (ref (exact $1)))
  (local $0 (ref string))
  (local $3 (ref $3))
  (drop
   (block $block (result (ref (exact $1)))
    (ref.cast (ref (exact $1))
     (br_if $block
      (block (result (ref (exact $1)))
       (local.set $1
        (struct.new_default $1)
       )
       (local.set $0
        (string.const "\f0\90\8d\88953\c2\a3")
       )
       (local.get $1)
      )
      (if (result i32)
       (array.len
        (local.tee $3
         (array.new_default $3
          (i32.const 0)
         )
        )
       )
       (then
        (string.encode_wtf16_array
         (local.get $0)
         (local.get $3)
         (i32.const 0)
        )
       )
       (else
        (i32.const 0)
       )
      )
     )
    )
   )
  )
 )
)

;; Element segments constrain their inputs. We cannot generalize $g here.
(module
  ;; CHECK:      (type $f (func))
  (type $f (func))

  ;; CHECK:      (global $g (ref null $f) (ref.null nofunc))
  (global $g (ref null $f) (ref.null $f))

  ;; CHECK:      (table $t 22 funcref)
  (table $t 22 funcref)

  ;; CHECK:      (elem $e (ref null $f) (item (global.get $g)))
  (elem $e (ref null $f) (item (global.get $g)))
)

;; Check we do not error on unreachability and uninhabitable types.
(module
  ;; CHECK:      (type $0 (func (result i32)))

  ;; CHECK:      (func $test (type $0) (result i32)
  ;; CHECK-NEXT:  (ref.eq
  ;; CHECK-NEXT:   (ref.cast (ref (shared none))
  ;; CHECK-NEXT:    (ref.null (shared none))
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test (result i32)
    (ref.eq
      (ref.cast (ref (shared none))
        (ref.null (shared none))
      )
      (unreachable)
    )
  )
)

;; Check we do not error on an exported global with no other uses.
(module
  ;; CHECK:      (global $g i32 (i32.const 0))
  (global $g i32 (i32.const 0))
  ;; CHECK:      (export "__data_end" (global $g))
  (export "__data_end" (global $g))
)

;; Mix shared and unshared in unreachable code.
(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (func $test (type $0)
  ;; CHECK-NEXT:  (ref.eq
  ;; CHECK-NEXT:   (block (result (ref null (shared none)))
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:    (ref.null (shared none))
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (ref.eq
      (block (result (ref null (shared none)))
        (unreachable)
        (ref.null (shared none))
      )
      (unreachable)
    )
  )
)

;; TODOtuple update in global
(;;
(module
 (type $t (sub (struct)))
 (type $t_1 (sub $t (struct)))
 (global $g (tuple i32 (ref null $t)) (tuple.make 2
  (i32.const 0)
  (struct.new_default $t_1)
 ))
)
;;)
