;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; Check with and without trapsNeverHappen.

;; RUN: foreach %s %t wasm-opt --type-generalizing -all      -S -o - | filecheck %s
;; RUN: foreach %s %t wasm-opt --type-generalizing -all -tnh -S -o - | filecheck %s --check-prefix=TNH__

;; When traps cannot happen, a ref.cast does not constrain the global, and can
;; even be generalized itself. When traps can happen (normally) we cannot do
;; anything here.
(module
  ;; CHECK:      (type $A (struct))
  ;; TNH__:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $g (mut (ref $A)) (struct.new_default $A))
  ;; TNH__:      (type $1 (func))

  ;; TNH__:      (global $g (mut anyref) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.cast (ref $A)
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; TNH__:      (func $test (type $1)
  ;; TNH__-NEXT:  (drop
  ;; TNH__-NEXT:   (ref.cast anyref
  ;; TNH__-NEXT:    (global.get $g)
  ;; TNH__-NEXT:   )
  ;; TNH__-NEXT:  )
  ;; TNH__-NEXT: )
  (func $test
    (drop
      (ref.cast (ref $A)
        (global.get $g)
      )
    )
  )
)

