;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --type-generalizing -all -S -o - | filecheck %s

;; With no constraints on it, this global can be anyref.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (global $g (mut anyref) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))
)

;; A global.get constrains us as it feeds into a ref.eq, so we must be eq.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $g (mut eqref) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.eq
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (ref.eq
        (global.get $g)
        (global.get $g)
      )
    )
  )
)

;; Exported globals are roots: we do not change their types.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $g (mut (ref $A)) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (export "g" (global $g))
  (export "g" (global $g))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.eq
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    (drop
      (ref.eq
        (global.get $g)
        (global.get $g)
      )
    )
  )
)

;; One global influences another. Here $g has two constraints: the exported
;; global $exp-nn which requires non-null any, and the ref.eq which requires
;; nullable eq. Together, we end up with non-null eq.
(module
  ;; CHECK:      (type $A (struct))
  (type $A (struct))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (global $exp-nn (mut (ref any)) (struct.new_default $A))
  (global $exp-nn (mut (ref any)) (struct.new $A))

  ;; CHECK:      (global $g (mut (ref eq)) (struct.new_default $A))
  (global $g (mut (ref $A)) (struct.new $A))

  ;; CHECK:      (export "exp" (global $exp-nn))
  (export "exp" (global $exp-nn))

  ;; CHECK:      (func $test (type $1)
  ;; CHECK-NEXT:  (global.set $exp-nn
  ;; CHECK-NEXT:   (global.get $g)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.eq
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:    (global.get $g)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test
    ;; Use $g in a set to the exported global, and in a ref.eq.
    (global.set $exp-nn
      (global.get $g)
    )
    (drop
      (ref.eq
        (global.get $g)
        (global.get $g)
      )
    )
  )
)

;; TODO: imports

