;; NOTE: Assertions have been generated by update_lit_checks.py --output=fuzz-exec and should not be edited.

;; RUN: wasm-opt %s -all --fuzz-exec -o /dev/null 2>&1 | filecheck %s

(module
  (type $prototypes (array (mut externref)))
  (type $funcs (array (mut funcref)))
  (type $data (array (mut i8)))
  (type $configureAll (func (param (ref null $prototypes)) (param (ref null $funcs)) (param (ref null $data)) (param externref)))

  (import "wasm:js-prototypes" "configureAll" (func $configureAll (type $configureAll)))

  (import "fuzzing-support" "log-i32" (func $log-i32 (param i32)))

  (data $data "12345678")
  (elem $prototypes externref (ref.null extern))
  (elem $funcs funcref (ref.func $js-called))

  (start $start)

  (func $start
    (call $configureAll
      (array.new_elem $prototypes $prototypes (i32.const 0) (i32.const 1))
      (array.new_elem $funcs $funcs (i32.const 0) (i32.const 1))
      (array.new_data $data $data (i32.const 0) (i32.const 8))
      (ref.null extern)
    )
  )

  (func $js-called
  )

  ;; CHECK:      [fuzz-exec] calling export
  ;; CHECK-NEXT: warning: no passes specified, not doing any work
  ;; CHECK-NEXT: [LoggingExternalInterface ignoring an unknown import wasm:js-prototypes . configureAll
  (func $export (export "export")
  )
)
;; CHECK:      [fuzz-exec] calling export
;; CHECK-NEXT: [fuzz-exec] comparing export
