;; NOTE: Assertions have been generated by update_lit_checks.py --output=fuzz-exec and should not be edited.

;; RUN: wasm-opt %s -all --fuzz-exec -q -o /dev/null 2>&1 | filecheck %s

;; Test we can execute imported string constants and operations.

(module
  (type $array16 (array (mut i16)))

  (import "\'" "foo" (global $foo (ref extern)))

  (import "\'" "bar" (global $bar (ref extern)))

  (import "wasm:js-string" "concat" (func $concat (param externref externref) (result (ref extern))))

  (func $string.concat (export "string.concat") (result (ref extern))
    (call $concat
      (global.get $foo)
      (global.get $bar)
    )
  )
)
