#!/usr/bin/python3

import os
import argparse
import time
import logging

from google import genai
from google.genai import types


# Global arguments from the user
args = None


# --- Setup Logging ---
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

prompt_index = 0

def log_prompt_or_response(contents, what):
    if not args.prompt_history_dir:
        return

    global prompt_index
    # New prompts bump the index (responses do not).
    if what == 'prompt':
        prompt_index += 1
    filename = os.path.join(args.prompt_history_dir, f'{what}-{prompt_index}.txt')
    open(filename, 'w').write(contents)


def log_prompt(contents):
    return log_prompt_or_response(contents, 'prompt')


def log_response(contents):
    return log_response_or_response(contents, 'response')


# LLM client handling

SYSTEM_INSTRUCTION = '''
You are a software engineer that knows Python, with experience with fuzzers as
a way to find bugs by generating random testcases.
'''


class GeminiClient:
    def __init__(self):
        # Looks for GEMINI_API_KEY env var automatically.
        self.client = genai.Client()
        self.model = args.model
        self.temperature = args.temperature
        self.system_instruction = SYSTEM_INSTRUCTION
        self.chat_session = None

    def _execute_with_retry(self, func, *args, max_retries=5, **kwargs):
        """
        Handles exponential backoff for rate limits and transient server errors.
        """
        for attempt in range(max_retries):
            try:
                return func(*args, **kwargs)
            except Exception as e:
                # The new SDK raises various exceptions; we check for common retryable ones
                err_msg = str(e).lower()
                if "429" in err_msg or "rate limit" in err_msg:
                    wait = (2 ** attempt) + 1
                    logger.warning(f"Rate limit hit. Retrying in {wait}s...")
                    time.sleep(wait)
                elif "500" in err_msg or "503" in err_msg or "deadline" in err_msg:
                    wait = (2 ** attempt)
                    logger.warning(f"Server error/Timeout. Retrying in {wait}s...")
                    time.sleep(wait)
                else:
                    logger.error(f"Non-retryable error: {e}")
                    raise e
        raise Exception("Maximum retries reached. Operation failed.")

    def generate_single(self, prompt):
        """Standard one-off prompt/response."""
        config = types.GenerateContentConfig(
            system_instruction=self.system_instruction,
            temperature=self.temperature,
        )

        log_prompt(prompt)
        
        response = self._execute_with_retry(
            self.client.models.generate_content,
            model=self.model,
            contents=prompt,
            config=config
        )

        log_response(response.text)

        return response.text

    def send_chat(self, message):
        """Handles stateful conversation."""
        if self.chat_session is None:
            # Initialize the chat session if it doesn't exist
            config = types.GenerateContentConfig(
                system_instruction=self.system_instruction,
                temperature=self.temperature,
            )
            self.chat_session = self.client.chats.create(
                model=self.model,
                config=config
            )

        log_prompt(message)

        response = self._execute_with_retry(
            self.chat_session.send_message,
            message=message
        )

        log_response(response.text)

        return response.text

    def end_chat(self):
        self.chat_session = None


# Bundle text files into a prompt, with a header for each
def bundle_files(filenames):
    chunks = []
    for filename in filenames:
        # Header
        chunk = f">>>> {os.path.basename(filename)}\n"

        # Content
        content = open(filename, encoding='utf-8').read()
        chunk += content
        # Ensure there's a newline at the end of the content
        if not content.endswith('\n'):
            chunk += '\n'
        # Add an extra newline for clear separation between files
        chunk += '\n'
        chunks.append(chunk)

    return '\n'.join(chunks)


# Generate the initial fuzzer

FUZZER_GOALS = '''

The fuzzer's overall goals are:

* The outputs should be diverse, that is, many different testcases can be
  generated by this fuzzer, with many different aspects to them. Some testcases
  might be small, others large; some might have more of one element and others
  more of another, or a mixture; and so forth. We want to generate many varied
  testcases so we have the best chance to generate ones that reveal bugs.
* The outputs should be valid, in the sense explained below.

The specific testcases the fuzzer generates are WebAssembly and JavaScript
combination programs. Each testcase contains a JavaScript file that loads a
corresponding WebAssembly file, then runs and interacts with it.

Our specific focus is on security and correctness. We are not interested in
simple parsing bugs, that is, if the WebAssembly or the JavaScript does not even
parse, that is not useful. We want the programs to run and do useful, realistic
work. While running them we will use tools like Address Sanitizer to look for
memory problems, and we will compare the outputs in different modes (JIT vs no
JIT, for example) to look for correctness issues.

It is ok if some testcases throw an exception or trap. Such errors do not need
to be avoided entirely, but we do want most of the code to mostly run, so that
we actually test lots of executing code.

Some tips for achieving these goals:

* Decide on rates of certain things. For example, perhaps one program has lots
  of calls while the other has few. Either at the program or function level, you
  can pick a rate of things like calls, and use it in that scope. Different
  programs and functions will therefore vary when you pick a different rate of
  calls in them.

'''

INITIAL_GENERATION_PROMPT = '''
Write a fuzzer in Python that generates things similar to the examples below.

The fuzzer should take a single commandline parameter, and use that number to
deterministically generate a testcase (this determinism makes it easy to debug
the fuzzer itself). How it generates the testcase given a number is arbitrary
and you can do anything you want, but try to do well on the goals below.

''' + FUZZER_GOALS + '''

The following pairs of wasm+js are examples of useful, working programs in the
style we would like the fuzzer to generate. That is, the fuzzer should be
capable of generating programs generally similar to them, but of course
individual testcases may be very different. The fuzzer should be able to
generate testcases that are generally similar to combinations of them as well,
that is, combining interesting elements from different examples here.
'''


def generate_initial_fuzzer():
    print(f"💼 Generating initial fuzzer")

    client = GeminiClient(model, temperature):

# Main workflow.
def work():
    # Create the initial fuzzer, if there is none.
    if not os.path.exists(args.fuzzer_file):
        generate_initial_fuzzer()

    # Iterately improve the fuzzer.
    try:
        for i in range(args.max_iters):
            improve_fuzzer()
    except KeyboardInterrupt:
        print("🛑 Stopping by user request.")
        break


def main():
    parser = argparse.ArgumentParser(description="SlopFuzz")
    parser.add_argument("--model", type=str, default="gemini-3-flash-preview", help="Model ID")
    parser.add_argument("--temperature", type=float, default=0.7, help="Creativity temperature")
    parser.add_argument("--fuzzer-file", type=str, help="File to write the fuzzer in (must be inside a git repo, as each successful update is committed)")
    parser.add_argument("--max-iters", type=int, default=1000, help="Maximum number of iterations to run")
    parser.add_argument("--prompt-history-dir", type=str, help="Directory to store the full history of prompts and responses (for debugging)")

    global args
    args = parser.parse_args()

    work()


if __name__ == "__main__":
    main()
