  /*
   * Copyright 2020 WebAssembly Community Group participants
   *
   * Licensed under the Apache License, Version 2.0 (the "License");
   * you may not use this file except in compliance with the License.
   * You may obtain a copy of the License at
   *
   *     http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing, software
   * distributed under the License is distributed on an "AS IS" BASIS,
   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   * See the License for the specific language governing permissions and
   * limitations under the License.
   */

  //=============================================================================
  // This is an AUTOGENERATED file, even though it looks human-readable! Do not
  // edit it by hand, instead edit the generator, gen-exprs.py
  //
  // You can and should treat it like human-written code in all other ways,
  // though, like reviewing it in a PR, etc.
  //=============================================================================

case Expression::NopId: {
  auto* copy = wasm.allocator.alloc<Nop>();
  *task.destPointer = copy;
  break;
}
case Expression::BlockId: {
  auto* source = task.source->cast<Block>();
  auto* copy = wasm.allocator.alloc<Block>();
  *task.destPointer = copy;
  copy->name = source->name;
  copy->list.resize(source->list.size());
  for (Index i = 0; i < source->list.size(); i++) {
    handleChild(source->list[i], &copy->list[i]);
  }
  break;
}
case Expression::IfId: {
  auto* source = task.source->cast<If>();
  auto* copy = wasm.allocator.alloc<If>();
  *task.destPointer = copy;
  handleChild(source->condition, &copy->condition);
  handleChild(source->ifTrue, &copy->ifTrue);
  handleChild(source->ifFalse, &copy->ifFalse);
  break;
}
case Expression::LoopId: {
  auto* source = task.source->cast<Loop>();
  auto* copy = wasm.allocator.alloc<Loop>();
  *task.destPointer = copy;
  copy->name = source->name;
  handleChild(source->body, &copy->body);
  break;
}
case Expression::BreakId: {
  auto* source = task.source->cast<Break>();
  auto* copy = wasm.allocator.alloc<Break>();
  *task.destPointer = copy;
  copy->name = source->name;
  handleChild(source->value, &copy->value);
  handleChild(source->condition, &copy->condition);
  break;
}
case Expression::SwitchId: {
  auto* source = task.source->cast<Switch>();
  auto* copy = wasm.allocator.alloc<Switch>();
  *task.destPointer = copy;
  copy->targets = source->targets;
  copy->default_ = source->default_;
  handleChild(source->value, &copy->value);
  handleChild(source->condition, &copy->condition);
  break;
}
case Expression::CallId: {
  auto* source = task.source->cast<Call>();
  auto* copy = wasm.allocator.alloc<Call>();
  *task.destPointer = copy;
  copy->operands.resize(source->operands.size());
  for (Index i = 0; i < source->operands.size(); i++) {
    handleChild(source->operands[i], &copy->operands[i]);
  }
  copy->target = source->target;
  copy->isReturn = source->isReturn;
  break;
}
case Expression::CallIndirectId: {
  auto* source = task.source->cast<CallIndirect>();
  auto* copy = wasm.allocator.alloc<CallIndirect>();
  *task.destPointer = copy;
  copy->sig = source->sig;
  copy->operands.resize(source->operands.size());
  for (Index i = 0; i < source->operands.size(); i++) {
    handleChild(source->operands[i], &copy->operands[i]);
  }
  handleChild(source->target, &copy->target);
  copy->isReturn = source->isReturn;
  break;
}
case Expression::LocalGetId: {
  auto* source = task.source->cast<LocalGet>();
  auto* copy = wasm.allocator.alloc<LocalGet>();
  *task.destPointer = copy;
  copy->index = source->index;
  break;
}
case Expression::LocalSetId: {
  auto* source = task.source->cast<LocalSet>();
  auto* copy = wasm.allocator.alloc<LocalSet>();
  *task.destPointer = copy;
  copy->index = source->index;
  handleChild(source->value, &copy->value);
  break;
}
case Expression::GlobalGetId: {
  auto* source = task.source->cast<GlobalGet>();
  auto* copy = wasm.allocator.alloc<GlobalGet>();
  *task.destPointer = copy;
  copy->name = source->name;
  break;
}
case Expression::GlobalSetId: {
  auto* source = task.source->cast<GlobalSet>();
  auto* copy = wasm.allocator.alloc<GlobalSet>();
  *task.destPointer = copy;
  copy->name = source->name;
  handleChild(source->value, &copy->value);
  break;
}
case Expression::LoadId: {
  auto* source = task.source->cast<Load>();
  auto* copy = wasm.allocator.alloc<Load>();
  *task.destPointer = copy;
  copy->bytes = source->bytes;
  copy->signed_ = source->signed_;
  copy->offset = source->offset;
  copy->align = source->align;
  copy->isAtomic = source->isAtomic;
  handleChild(source->ptr, &copy->ptr);
  break;
}
case Expression::StoreId: {
  auto* source = task.source->cast<Store>();
  auto* copy = wasm.allocator.alloc<Store>();
  *task.destPointer = copy;
  copy->bytes = source->bytes;
  copy->offset = source->offset;
  copy->align = source->align;
  copy->isAtomic = source->isAtomic;
  handleChild(source->ptr, &copy->ptr);
  handleChild(source->value, &copy->value);
  copy->valueType = source->valueType;
  break;
}
case Expression::AtomicRMWId: {
  auto* source = task.source->cast<AtomicRMW>();
  auto* copy = wasm.allocator.alloc<AtomicRMW>();
  *task.destPointer = copy;
  copy->op = source->op;
  copy->bytes = source->bytes;
  copy->offset = source->offset;
  handleChild(source->ptr, &copy->ptr);
  handleChild(source->value, &copy->value);
  break;
}
case Expression::AtomicCmpxchgId: {
  auto* source = task.source->cast<AtomicCmpxchg>();
  auto* copy = wasm.allocator.alloc<AtomicCmpxchg>();
  *task.destPointer = copy;
  copy->bytes = source->bytes;
  copy->offset = source->offset;
  handleChild(source->ptr, &copy->ptr);
  handleChild(source->expected, &copy->expected);
  handleChild(source->replacement, &copy->replacement);
  break;
}
case Expression::AtomicWaitId: {
  auto* source = task.source->cast<AtomicWait>();
  auto* copy = wasm.allocator.alloc<AtomicWait>();
  *task.destPointer = copy;
  copy->offset = source->offset;
  handleChild(source->ptr, &copy->ptr);
  handleChild(source->expected, &copy->expected);
  handleChild(source->timeout, &copy->timeout);
  copy->expectedType = source->expectedType;
  break;
}
case Expression::AtomicNotifyId: {
  auto* source = task.source->cast<AtomicNotify>();
  auto* copy = wasm.allocator.alloc<AtomicNotify>();
  *task.destPointer = copy;
  copy->offset = source->offset;
  handleChild(source->ptr, &copy->ptr);
  handleChild(source->notifyCount, &copy->notifyCount);
  break;
}
case Expression::AtomicFenceId: {
  auto* source = task.source->cast<AtomicFence>();
  auto* copy = wasm.allocator.alloc<AtomicFence>();
  *task.destPointer = copy;
  copy->order = source->order;
  break;
}
case Expression::SIMDExtractId: {
  auto* source = task.source->cast<SIMDExtract>();
  auto* copy = wasm.allocator.alloc<SIMDExtract>();
  *task.destPointer = copy;
  copy->op = source->op;
  handleChild(source->vec, &copy->vec);
  copy->index = source->index;
  break;
}
case Expression::SIMDReplaceId: {
  auto* source = task.source->cast<SIMDReplace>();
  auto* copy = wasm.allocator.alloc<SIMDReplace>();
  *task.destPointer = copy;
  copy->op = source->op;
  handleChild(source->vec, &copy->vec);
  copy->index = source->index;
  handleChild(source->value, &copy->value);
  break;
}
case Expression::SIMDShuffleId: {
  auto* source = task.source->cast<SIMDShuffle>();
  auto* copy = wasm.allocator.alloc<SIMDShuffle>();
  *task.destPointer = copy;
  handleChild(source->left, &copy->left);
  handleChild(source->right, &copy->right);
  copy->mask = source->mask;
  break;
}
case Expression::SIMDTernaryId: {
  auto* source = task.source->cast<SIMDTernary>();
  auto* copy = wasm.allocator.alloc<SIMDTernary>();
  *task.destPointer = copy;
  copy->op = source->op;
  handleChild(source->a, &copy->a);
  handleChild(source->b, &copy->b);
  handleChild(source->c, &copy->c);
  break;
}
case Expression::SIMDShiftId: {
  auto* source = task.source->cast<SIMDShift>();
  auto* copy = wasm.allocator.alloc<SIMDShift>();
  *task.destPointer = copy;
  copy->op = source->op;
  handleChild(source->vec, &copy->vec);
  handleChild(source->shift, &copy->shift);
  break;
}
case Expression::SIMDLoadId: {
  auto* source = task.source->cast<SIMDLoad>();
  auto* copy = wasm.allocator.alloc<SIMDLoad>();
  *task.destPointer = copy;
  copy->op = source->op;
  copy->offset = source->offset;
  copy->align = source->align;
  handleChild(source->ptr, &copy->ptr);
  break;
}
case Expression::MemoryInitId: {
  auto* source = task.source->cast<MemoryInit>();
  auto* copy = wasm.allocator.alloc<MemoryInit>();
  *task.destPointer = copy;
  copy->segment = source->segment;
  handleChild(source->dest, &copy->dest);
  handleChild(source->offset, &copy->offset);
  handleChild(source->size, &copy->size);
  break;
}
case Expression::DataDropId: {
  auto* source = task.source->cast<DataDrop>();
  auto* copy = wasm.allocator.alloc<DataDrop>();
  *task.destPointer = copy;
  copy->segment = source->segment;
  break;
}
case Expression::MemoryCopyId: {
  auto* source = task.source->cast<MemoryCopy>();
  auto* copy = wasm.allocator.alloc<MemoryCopy>();
  *task.destPointer = copy;
  handleChild(source->dest, &copy->dest);
  handleChild(source->source, &copy->source);
  handleChild(source->size, &copy->size);
  break;
}
case Expression::MemoryFillId: {
  auto* source = task.source->cast<MemoryFill>();
  auto* copy = wasm.allocator.alloc<MemoryFill>();
  *task.destPointer = copy;
  handleChild(source->dest, &copy->dest);
  handleChild(source->value, &copy->value);
  handleChild(source->size, &copy->size);
  break;
}
case Expression::ConstId: {
  auto* source = task.source->cast<Const>();
  auto* copy = wasm.allocator.alloc<Const>();
  *task.destPointer = copy;
  copy->value = source->value;
  break;
}
case Expression::UnaryId: {
  auto* source = task.source->cast<Unary>();
  auto* copy = wasm.allocator.alloc<Unary>();
  *task.destPointer = copy;
  copy->op = source->op;
  handleChild(source->value, &copy->value);
  break;
}
case Expression::BinaryId: {
  auto* source = task.source->cast<Binary>();
  auto* copy = wasm.allocator.alloc<Binary>();
  *task.destPointer = copy;
  copy->op = source->op;
  handleChild(source->left, &copy->left);
  handleChild(source->right, &copy->right);
  break;
}
case Expression::SelectId: {
  auto* source = task.source->cast<Select>();
  auto* copy = wasm.allocator.alloc<Select>();
  *task.destPointer = copy;
  handleChild(source->ifTrue, &copy->ifTrue);
  handleChild(source->ifFalse, &copy->ifFalse);
  handleChild(source->condition, &copy->condition);
  break;
}
case Expression::DropId: {
  auto* source = task.source->cast<Drop>();
  auto* copy = wasm.allocator.alloc<Drop>();
  *task.destPointer = copy;
  handleChild(source->value, &copy->value);
  break;
}
case Expression::ReturnId: {
  auto* source = task.source->cast<Return>();
  auto* copy = wasm.allocator.alloc<Return>();
  *task.destPointer = copy;
  handleChild(source->value, &copy->value);
  break;
}
case Expression::MemorySizeId: {
  auto* source = task.source->cast<MemorySize>();
  auto* copy = wasm.allocator.alloc<MemorySize>();
  *task.destPointer = copy;
  copy->ptrType = source->ptrType;
  break;
}
case Expression::MemoryGrowId: {
  auto* source = task.source->cast<MemoryGrow>();
  auto* copy = wasm.allocator.alloc<MemoryGrow>();
  *task.destPointer = copy;
  handleChild(source->delta, &copy->delta);
  copy->ptrType = source->ptrType;
  break;
}
case Expression::UnreachableId: {
  auto* copy = wasm.allocator.alloc<Unreachable>();
  *task.destPointer = copy;
  break;
}
case Expression::PopId: {
  auto* copy = wasm.allocator.alloc<Pop>();
  *task.destPointer = copy;
  break;
}
case Expression::RefNullId: {
  auto* copy = wasm.allocator.alloc<RefNull>();
  *task.destPointer = copy;
  break;
}
case Expression::RefIsNullId: {
  auto* source = task.source->cast<RefIsNull>();
  auto* copy = wasm.allocator.alloc<RefIsNull>();
  *task.destPointer = copy;
  handleChild(source->value, &copy->value);
  break;
}
case Expression::RefFuncId: {
  auto* source = task.source->cast<RefFunc>();
  auto* copy = wasm.allocator.alloc<RefFunc>();
  *task.destPointer = copy;
  copy->func = source->func;
  break;
}
case Expression::RefEqId: {
  auto* source = task.source->cast<RefEq>();
  auto* copy = wasm.allocator.alloc<RefEq>();
  *task.destPointer = copy;
  handleChild(source->left, &copy->left);
  handleChild(source->right, &copy->right);
  break;
}
case Expression::TryId: {
  auto* source = task.source->cast<Try>();
  auto* copy = wasm.allocator.alloc<Try>();
  *task.destPointer = copy;
  handleChild(source->body, &copy->body);
  handleChild(source->catchBody, &copy->catchBody);
  break;
}
case Expression::ThrowId: {
  auto* source = task.source->cast<Throw>();
  auto* copy = wasm.allocator.alloc<Throw>();
  *task.destPointer = copy;
  copy->event = source->event;
  copy->operands.resize(source->operands.size());
  for (Index i = 0; i < source->operands.size(); i++) {
    handleChild(source->operands[i], &copy->operands[i]);
  }
  break;
}
case Expression::RethrowId: {
  auto* source = task.source->cast<Rethrow>();
  auto* copy = wasm.allocator.alloc<Rethrow>();
  *task.destPointer = copy;
  handleChild(source->exnref, &copy->exnref);
  break;
}
case Expression::BrOnExnId: {
  auto* source = task.source->cast<BrOnExn>();
  auto* copy = wasm.allocator.alloc<BrOnExn>();
  *task.destPointer = copy;
  copy->name = source->name;
  copy->event = source->event;
  handleChild(source->exnref, &copy->exnref);
  copy->sent = source->sent;
  break;
}
case Expression::TupleMakeId: {
  auto* source = task.source->cast<TupleMake>();
  auto* copy = wasm.allocator.alloc<TupleMake>();
  *task.destPointer = copy;
  copy->operands.resize(source->operands.size());
  for (Index i = 0; i < source->operands.size(); i++) {
    handleChild(source->operands[i], &copy->operands[i]);
  }
  break;
}
case Expression::TupleExtractId: {
  auto* source = task.source->cast<TupleExtract>();
  auto* copy = wasm.allocator.alloc<TupleExtract>();
  *task.destPointer = copy;
  handleChild(source->tuple, &copy->tuple);
  copy->index = source->index;
  break;
}
case Expression::I31NewId: {
  auto* source = task.source->cast<I31New>();
  auto* copy = wasm.allocator.alloc<I31New>();
  *task.destPointer = copy;
  handleChild(source->value, &copy->value);
  break;
}
case Expression::I31GetId: {
  auto* source = task.source->cast<I31Get>();
  auto* copy = wasm.allocator.alloc<I31Get>();
  *task.destPointer = copy;
  handleChild(source->i31, &copy->i31);
  copy->signed_ = source->signed_;
  break;
}
case Expression::RefTestId: {
  auto* copy = wasm.allocator.alloc<RefTest>();
  *task.destPointer = copy;
  break;
}
case Expression::RefCastId: {
  auto* copy = wasm.allocator.alloc<RefCast>();
  *task.destPointer = copy;
  break;
}
case Expression::BrOnCastId: {
  auto* copy = wasm.allocator.alloc<BrOnCast>();
  *task.destPointer = copy;
  break;
}
case Expression::RttCanonId: {
  auto* copy = wasm.allocator.alloc<RttCanon>();
  *task.destPointer = copy;
  break;
}
case Expression::RttSubId: {
  auto* copy = wasm.allocator.alloc<RttSub>();
  *task.destPointer = copy;
  break;
}
case Expression::StructNewId: {
  auto* copy = wasm.allocator.alloc<StructNew>();
  *task.destPointer = copy;
  break;
}
case Expression::StructGetId: {
  auto* copy = wasm.allocator.alloc<StructGet>();
  *task.destPointer = copy;
  break;
}
case Expression::StructSetId: {
  auto* copy = wasm.allocator.alloc<StructSet>();
  *task.destPointer = copy;
  break;
}
case Expression::ArrayNewId: {
  auto* copy = wasm.allocator.alloc<ArrayNew>();
  *task.destPointer = copy;
  break;
}
case Expression::ArrayGetId: {
  auto* copy = wasm.allocator.alloc<ArrayGet>();
  *task.destPointer = copy;
  break;
}
case Expression::ArraySetId: {
  auto* copy = wasm.allocator.alloc<ArraySet>();
  *task.destPointer = copy;
  break;
}
case Expression::ArrayLenId: {
  auto* copy = wasm.allocator.alloc<ArrayLen>();
  *task.destPointer = copy;
  break;
}
